### ISSUE TITLE
Rendu partiel de template

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#100]
*suite de #93*

> Faire en sorte de pouvoir spécifier un autre chemin de templates au moment de rendre les chansons chordpro.

Comme [évoqué](https://github.com/patacrep/patacrep/issues/93#issuecomment-140987995), je ne pense pas que cela soit très pertinent (du moins pour le moment).

**Comment by paternal** [comment]
Je pense que la vraie question, c'est : Produire une version HTML de la chanson.

**Comment by oliverpool** [comment]
> Produire une version HTML de la chanson.

Je dirai plutôt: Produire une version HTML du *corps du chant*

En effet, ce qui concerne l'entête est assez spécifique au contexte (avec des liens sur l'artiste vers des pages internes par exemple).

En revanche, le corps du chant ne devrait pas nécessiter de traitement particulier.

Du coup je suis partant pour écrire un template HTML dans patacrep pour le corps du chant (et éventuellement le reste de l'entête) si je peux avoir une **méthode pour récupérer juste le corps du chant dans le format souhaité** (à savoir HTML ou chordpro ou autre).

Qu'en penses-tu ?

**Comment by oliverpool** [comment]
Si on part sur un "Rendu partiel de template" (auquel je suis très favorable), on peut fusionner cette issue avec la #99

**Comment by paternal** [comment]
Je pense que ce sont deux problèmes différents.

- Le rendu du corps de chordpro peut se faire avec l'implémentation actuelle, avec les templates jinja (sans même que patanet sache qu'il utilise jinja).
- Le rendu HTML doit être fait par Django. C'est une partie du travail qui est spécifique à patanet : utilisation de CSS utilisé par django, intégration d'images et de partition servies par django, etc. Ça peut tout à fait être fait en Django.

Je peux faire une ébauche des deux points entre deux biberons.

**Comment by oliverpool** [comment]
J'ai une branche en cours: https://github.com/patacrep/patacrep/compare/master...partial_template_rendering

**Comment by oliverpool** [comment]
Et je compte implémenter un template 'HTML' dans patacrep.
Patanet ne se servira que de la partie `body` de ce template (avec son propre CSS), et écrira son propre HTML pour l'entête.

**Comment by paternal** [comment]
Pas mal pour ces commits : je vois que nous avions la même idée en tête quasiment au caractère près. :smile: 

> Edit: ou presque, il restera un problème avec les fichiers liés (image, partition)

Sauf pour le rendu HTML où pour ces raisons, je maintient qu'il est plus pertinent de faire cela dans patanet, avec les templates django.

**Comment by paternal** [comment]
Je reviens à la charge, avec une ébauche de solution.

Le problème avec la génération du code HTML dans patacrep, c'est qu'on perd tout le contexte django, et qu'on a plus accès à cet environnement (ce qui va poser problème pour les images, comme tu l'as signalé). Du coup, les [templates html actuels](https://github.com/patacrep/patacrep/tree/5ab211315ea73127c49c8304d51893931aa495cb/patacrep/songs/chordpro/data/html) ne sont pas mauvais : ils sont juste au mauvais endroit.

Je ne connais pas assez le code patanet pour le faire moi même, mais je pense qu'il faut : 

- créer une série [d'inclusion tags](https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/#inclusion-tags) (des commandes django qui rendent un autre template), dont le principal serait `render_song` ;
- pour [renrde la chanson](https://github.com/patacrep/patanet/blob/0f340c1a48b0b88048ff5fc6f1ad3f631565e29d/generator/templates/generator/show_song.html#L94), utiliser quelque chose comme `{{ render_song song }}` ;
- dans les templates html, pour chacun des éléments des ast, écrire les tags utiles, et utiliser `render_*`. Par exemple, pour [chords](https://github.com/patacrep/patacrep/blob/5ab211315ea73127c49c8304d51893931aa495cb/patacrep/songs/chordpro/data/html/content_chordlist), cela donnerait  quelque chose comme : 
~~~html
<span class="chord">
    {% for chord in content.chords %}
        {{ render_chord chord }}
    {% endfor %}
</span>
~~~

Le code de `render_song`, quant à lui, serait quelque chose comme : 
~~~python
@register.inclusion_tag('chordpro/song.html')
def render_song(song):
  return {
    'authors': song.authors,
    'titles': song.titles,
    ...
  }
~~~

**Comment by paternal** [comment]
La nuit porte conseil : même chose que mon commentaire précédent, mais on peut en plus faire une classe `Chordpr2HtmlSong` qui hérite de chordpro song, et on met toutes les fonctions `render_*` comme méthodes de cette classe. Comme ça, ça simplifie le passage d'arguments (même s'il faut toujours en passer) car toutes les informations générique sur la chanson sont accessibles dans `self`.

**Comment by oliverpool** [comment]
Je commence à comprendre ton idée et ça me plaît vraiment !

Dans l'idéal, je souhaiterais seulement un tag personnalisé: `render_ast`, qui se charge de reconnaître la classe (define, chord...) et de rendre le template (patacrep) en conséquence.

En gros un accès "simple" à [`_render_ast`](https://github.com/patacrep/patacrep/blob/6dd9bba5283d531beec1e56e5eb7e3babb04e761/patacrep/songs/chordpro/__init__.py#L57).
Pour pouvoir faire `{% render_e chord %}`

**Comment by paternal** [comment]
Le souci, si tu veux utiliser les [inclusion tags](https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/#inclusion-tags), c'est que j'ai l'impression que le template utilisé doit être défini à la définition de la fonction : donc je ne suis pas sûr qu'il soit possible de faire une méthode générique qui fonctionne pour tous les types d'AST.

À moins d'utiliser un seul template `song_ast.html`, qui contienne quelque chose comme (avec `node` étant l'instance de l'AST à utiliser) : 
~~~html
{% include node.template() %}
~~~

La méthode `_render_ast` serait alors :  
~~~python
@register.inclusion_tag('song_ast.html')
def _render_ast_html(self, node):
    return {'node': node}
~~~

**Comment by oliverpool** [comment]
Je pensais plutôt utiliser les templates de patacrep avec le tag `render_ast` (du coup mon tag retourne simplement une chaine de caractère - générée par patacrep)

Si je veux redefinir un template localement, je préfère l'écrire explicitement (avec le système de local).

**Comment by paternal** [comment]
Je vois deux soucis ici (en supposant que ce que tu proposes s'applique [à patacrep](https://github.com/patacrep/patacrep/blob/partial_template_rendering/patacrep/songs/chordpro/__init__.py)) : 

- Le `@register.simple_tag` est un objet de django. Cela voudrait dire qu'on faisant cela, on ajoute `django` comme dépendance à patacrep, alors qu'il n'est pas utile dans patacrep.
- En utilisant un `simple_tag`, tu perds toute l'information sur l'environnement Django. Ça ne pose aucun problème, sauf pour les images et partitions : il va falloir savoir avec quelle URL les servir. Et ça, c'est un boulot que fait très bien Django.

Ma proposition : [dans `patanet.generator.songs`](https://github.com/patacrep/patanet/blob/song_edition/generator/songs.py), on fait une sous-classe de `patacrep.songs.ChordproSong`. La fonction [`parse_song`](https://github.com/patacrep/patanet/blob/song_edition/generator/songs.py#L37) actuelle peut être transformée en *factory*, et la fonction `get_cover_url` en méthode.

~~~python
from patacrep.songs.chordpro import ChordproSong

class Chordpro2HtmlSong(ChordproSong):

    @register.inclusion_tag("songs/song.html")
    def render_song(self, song):
      return {'song': self}

    @register.inclusion_tag("songs/content_chords.html")
    def render_chord(self, chord):
        return {'chord': chord}

    # Et tous les autres `def render_*()`…

    @classmethod
    def parse_song(cls, filename):
       # [...]
       song = cls(datadir, relpath,config)
       # [...]
        return song

    def get_cover_url(self):
        return TODO
~~~

Les [templates HTML de patacrep](https://github.com/patacrep/patacrep/tree/partial_template_rendering/patacrep/songs/chordpro/data/html) ne sont pas mauvais, mais leur place est dans patanet (puisque, par exemple, pour rendre les images et partitions, on a besoin de l'environnement Django pour savoir quelle URL rendre).

**Comment by oliverpool** [comment]
Je pensais mettre le `@register.simple_tag` dans django uniquement.
Mon implémentation (assez brouillon) actuelle est dans les branches poc_html:
- [patanet](https://github.com/patacrep/patanet/compare/song_edition...poc_html_rendering)
- [patacrep](https://github.com/patacrep/patacrep/compare/partial_template_rendering...poc_html_rendering)

Pour les URLs, j'ai une autre idée: "décorer" la méthode `search_file`.
Si un chemin est trouvé, une fonction django se charge de retourner la bonne URL (à l'aide du chemin du fichier).
Cela pourrait aussi permettre de dresser la liste des fichiers externes requis par un fichier (voire par un carnet complet) et d'envisager un export (avec juste les fichiers requis)

**Comment by paternal** [comment]
[HS]J'ai en partie répondu à ta question « À quoi sert l'argument `config` » ici #102[/HS]

Peux-tu expliquer pourquoi tu penses que les templates HTML, comme l'ensemble de la mécanique du rendu HTML, doivent se trouver dans patacrep ? J'ai l'impression que c'est ce qui divise nos opinions sur le sujet.

Mon opinion : Le rendu HTML n'est pas utile dans patacrep mais seulement dans patanet ; par cohérence, mieux vaut le mettre dans patanet. La production de HTML dans patanet est faite avec Django ; ça me parait bizarre de rendre les chansons (et seulement les chansons) avec un autre moteur de rendu (jinja), d'autant plus que l'on se prive de la logique chordpro pour la production d'URL (images et partitions).

**Comment by oliverpool** [comment]
> J'ai l'impression que c'est ce qui divise nos opinions sur le sujet.

Effectivement, mon point de vue était un peu différent, je m'imagine la répartition des tâches suivante :
* patacrep est chargé de l'interprétation et du rendu des chants (avec différents formats d'entrée/sortie).
* patanet (tout comme patagui) est chargé de proposer une interface pour manipuler patacrep. 

Ainsi patanet a sa propre base de donnée des artistes et des titres, mais quand il s'agit d'afficher le rendu d'un chant (html en l'occurence), il est plus pertinent de faire appel à patacrep.

Du coup je suis enclins à proposer un rendu HTML *standard* dans patacrep (qui pourrait servir à d'autres utilisateurs/développeurs), sachant que cela n'empêche en rien patanet d'organiser son propre rendu si il le souhaite (en s'inspirant de la structure de patacrep par exemple).

---

Concernant les fichiers liés, je pense qu'il n'est pas souhaitable de résoudre cela localement (ie dans les templates `partition`, `image`, `cover`...), mais plutôt globalement  en "décorant" la méthode `search_file`.

**Comment by paternal** [comment]
> Concernant les fichiers liés, je pense qu'il n'est pas souhaitable de résoudre cela localement (ie dans les templates partition, image, cover...), mais plutôt globalement en "décorant" la méthode search_file.

Je ne comprends pas où tu veux en venir ; j'attends de voir l'implémentation :)

**Comment by oliverpool** [comment]
> Je ne comprends pas où tu veux en venir ; j'attends de voir l'implémentation :)

Voilà ce que j'avais en tête : https://github.com/patacrep/patanet/commit/46efc395a6942de240b2879f624b3dedd58cca1f
(sans statictag: https://github.com/patacrep/patanet/commit/6fc80dca9382153b7718d17bf9cab4faccea0828)

Cela a nécessité une légère modif sur patacrep : https://github.com/patacrep/patacrep/commit/efdb79cac94ccee4ec976d2c91cce508d52fd94d

**Comment by paternal** [comment]
Je propose moi aussi ma version : 

* patacrep : https://github.com/patacrep/patacrep/compare/partial_template_rendering...html_render
* patanet : https://github.com/patacrep/patanet/compare/0f340c1a48b0b88048ff5fc6f1ad3f631565e29d...html_render

Elle fonctionne également, y compris les images de chanson (cover) et les directives image (`{image: foo.png}`) (sauf que je n'ai pas cherché à configurer [staticfiles](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/) pour que ça fonctionne, mais j'ai l'URL correcte).

---

Concernant ton implémentation.

- Je dois dire que je trouve la définition et l'utilisation de `path_decorator` plutôt élégantes. J'aurai peut-être défini une nouvelle fonction (`song.file_url()`), ou surclasser la méthode existante, plutôt que redéfinir une méthode de la classe, mais pourquoi pas.
- Mais je ne vois toujours pas comment tu vas gérer les images et les parititons : tu vas récupérer le code HTML du corps de la chanson comme une grosse chaîne de caractères, et il faudra aller chercher là-dedans ce qui constitue l'inclusion d'une image, pour la remplacer par la bonne URL. Je ne vois pas comment faire ça de manière élégante.

**Comment by oliverpool** [comment]
Je dois avouer que ton implémentation est très souple (et plus complète que la mienne^^).

---

Pour les images et la jaquette, je comptais simplement écrire un fichier `html/content_cover` et `html/content_image`  ainsi:
```html
<img src="{{ song.cover_filepath }}">
```

Pour les partitions, peut-être simplement
```html
<object class="song-partition" data="{{ partition }}"></object>
```
Et rajouter du javascript pour l'afficher correctement (probablement avec un rendu en image)

Mais ta solution est plus souple dans le cas d'un rendu d'image (car il suffit alors de remplacer le tag HTML par `img` dans le code de patanet, sans perturber patacrep)

---

Proposition:
* on garde ton template (embarqué dans patanet).
* on rajoute une ligne dans `search_file`:
```py
if self.filepath_postprocess:
    return self.filepath_postprocess(fullpath)
else:
   return fullpath
```
Et on déplace mon décorateur dans une méthode `filepath_postprocess` de ta classe `ChordPro2Html` (et du coup le templatetag `datadir` peut-être supprimé)

**Comment by paternal** [comment]
> Je dois avouer que ton implémentation est très souple (et plus complète que la mienne^^).

J'ai re-réfléchi pendant la nuit à ton implémentation, et à quelques modifications près, elle me parait assez propre pour me convenir. :)

---

> Pour les images et la jaquette, je comptais simplement écrire un fichier `html/content_cover` et `html/content_image`  ainsi:
> ```html
> <img src="{{ song.cover_filepath }}">
> ```

Actuellement, ni les images ni la jaquette ne sont passées par `search_file()`. L'implémentation actuelle de ces fonctions est propre à LaTeX, et n'est utilisé que par LaTeX. On pourrait :

* faire une méthode virtuelle (qui lève `NotImplementedError`) dans [`Song`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/__init__.py#L65) (ou plutôt, qui ajoute une extension et cherche dans tous les datadirs le premier fichier qui correspond, pour pouvoir être utilisé par les autres implémentations);
* déplacer l'implémentation actuelle dans [`LatexSong`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/latex/__init__.py#L14) ;
* écrire une méthode qui renvoit son argument, sans changement, dans [`ChordproSong`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/__init__.py#L12) ;
* écrire une méthode qui renvoit `static(chemin_absolu_du_fichier(path))` dans `ChordPro2HtmlSong`. Elle correspond à ton décorateur `path_decorator`, qui est une bonne idée que j'ai transformée en méthode plutôt qu'en décorateur.

Et le template deviendrait pour les partitions, quelque chose comme :

~~~html
<object class="song-partition" data="{{ partition|search_partition }}"></object>
~~~

pour les images :

~~~html
<img src="{{ image|search_image }}">
~~~

pour la jaquette : 

~~~html
<img src="{{ song.cover_filepath|search_image }}">
~~~

Cette implémentation aurait en plus l'avantage de pouvoir modifier la fonction `search_partition` pour compiler la partition, placer l'image dans un fichier accessible, et renvoyer le code HTML d'une image de la partition.

Tout ceci est à mon avis fait plus simplement en transformant, comme je l'ai fait, la quasi-totalité du module [`generator/songs`](https://github.com/patacrep/patanet/blob/poc_html_rendering/generator/songs.py) en une classe `ChordPro2HtmlSong`.

Du coup, les méthodes `search_{file,image,partition}` deviennent des pré-processeurs à image, partition, fichiers, qui pourront être aussi utilisés dans les autres formats de fichier (je viens de donner l'exemple pour LaTeX et HTML, si jamais, comme tu l'évoquais, on voulait détecter l'ensemble des dépendances d'une chanson, on pourrait ajouter le code correspondant ici).

Un autre truc qui me parait pas trềs propre dans ton implémentation est le passage d'argument dans le filter [`render_ast`](https://github.com/patacrep/patanet/compare/song_edition...poc_html_rendering#diff-eee3814d2229166638954ea0e20b0d21R43) : je trouve ça plutôt moche ; je ne comprends pas à quoi correspondent les arguments. On doit pouvoir simplifier tout cela, quitte à faire deux fonctions différentes (l'une pour le rendu d'une chanson complète, l'autre pour le rendu d'une partie de lAST).

Bref, tout ça pour dire que ton implémentation, aux quelques modifications que je propose, me convient (et améliore même patacrep en ce qui concerne le nouveau rôle des `search_file`).

---

> Proposition:
> * on garde ton template (embarqué dans patanet).
> * on rajoute une ligne dans `search_file`:
> ```py
> if self.filepath_postprocess:
>     return self.filepath_postprocess(fullpath)
> else:
>    return fullpath
> ```
> Et on déplace mon décorateur dans une méthode `filepath_postprocess` de ta classe `ChordPro2Html` (et du coup le templatetag `datadir` peut-être supprimé)

Même problème que plus haut : `search_file` n'est jamais appelé, par défaut, sur les fichiers (images et partition). Je ne suis pas fan non plus de mon templatetag `datadir`, mais je n'ai pas trouvé mieux…

[HS]Au passage, dans le rendu de http://localhost:8000/fr/songs/le-donjon-de-naheulbeuk/marche-barbare/ avec ta version, les couplets à partir du 9e sont écrits sur une unique ligne (pas de retour à la ligne à la fin de chaque vers)[/HS]

**Comment by oliverpool** [comment]
Selon moi, le choix principal à faire actuellement concerne le stockage de ce template HTML: dans patanet, ou dans patacrep ?

Avantages du stockage dans patacrep:
* le template HTML est à côté des templates chordpro & LaTeX (si on supporte d'autres directives chordpro, les modifications sont regroupées)
* c'est le rôle de patacrep de s'occuper du rendu des chants et des carnets (quelque soit le format)
* cela permet à d'autres projets de profiter de ce rendu HTML sans efforts

Inconvénients:
* il faut décider d'un rendu HTML standard (pour les partition cela n'est pas évident - cf infra)
* si un projet autre veux personnalisé ce rendu, il doit réécrire tous les templates [je viens d'avoir une idée à ce propos - cf infra]

---

Après réflexion, je pense que pour les partitions il est plus logique d'écrire
```html
<a class="song-partition" data="{{ partition|search_partition }}">{{partition}}</a>
```
En effet, sémantiquement c'est un fichier lié (d'où le lien `a`). 
Si on veut améliorer le rendu (dans patanet par exemple), on peut alors rajouter un peu de javascript pour transformer ce lien en image (ou alors faire un rendu d'une partition lilypond en javascript ^^)

---

Concernant `search_file` je suis très favorables aux changements que tu proposes !
Le seul soucis, c'est lors de l'utilisation du filtre `image|search_image`, celui-ci à besoin d'une référence à l'objet `song` (`image|search_image_in:song` en utilisant un argument par exemple - ou dans l'autre sens: `song|search_image:image` - je préfère la première version)


---

Nouvelle idée
----
Le top du top, serait de pouvoir déclarer un dossier de templates alternatif qui remplace le template standard lorsque le fichier est présent.

Imaginons que patacrep s'occupe du rendu de chant en HTML et que les partitions sont rendus avec un tag `a` et que je souhaite un tag `img` dans mo projet. Alors je crée un dossier `custom_template\html` dans lequel je mets simplement un fichier `content_parition` et j'indique (lors de l'instanciation par exemple) le dossier `custom_template` et patacrep s'occupe du reste !

Je pense qu'une telle technique nécessiterai des changements dans la méthode `render` pour substituer les templates lorsque qu'il existe.

[HS]Ok, je regarde cela quand je rentre chez moi[/HS]

**Comment by oliverpool** [comment]
(en fait cette "nouvelle idée" n'est qu'une reprise de ton idée originale de permettre des templates personnalisés...)

**Comment by paternal** [comment]
> Le seul soucis, c'est lors de l'utilisation du filtre image|search_image, celui-ci à besoin d'une référence à l'objet song (image|search_image_in:song en utilisant un argument par exemple - ou dans l'autre sens: song|search_image:image - je préfère la première version)

Réponse rapide sur ce point précis : `search_file` est une méthode de la classe `Song` : elle a déjà accès à l'objet `song`, dans `self`.


Réponse à la suite plus tard…

**Comment by paternal** [comment]
> Réponse à la suite plus tard…

Mais globalement, ta synthèse m'a l'air pas mal…

**Comment by oliverpool** [comment]
Je vais continuer à coder un peu ma branche (poc_html_rendering) pour voir ce que ça peut donner

**Comment by oliverpool** [comment]
Voilà ce que ça donne (avec la "surcharge" de templates):
https://github.com/patacrep/patanet/commit/9d3ef71e8e9e118fbc3e0d105150fb0204f6aa4f
patacrep https://github.com/patacrep/patacrep/commit/56c7c39b05f2cd0203315a525c4f3e28935cc188

Il reste des choses à nettoyer (mon décorateur à virer, des méthode à déplacer dans la classe `Song`), mais l'idée générale me conviendrait !

**Comment by paternal** [comment]
@oliverpool : Juste pour éviter qu'on fasse du travail en même temps : je suis en train d'intégrer tout ce dont on a discuté…

**Comment by paternal** [comment]
Proposition prenant en compte nos dernières discussions (et quelques initiatives de ma part). Si ça te convient, tu acceptes. Sinon, tu modifies. :smile:  #103
