### ISSUE TITLE
Voir si l'argument `config` de `Song.parse()` peut-être supprimé

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#102]
Voir [`Song.parse()`](https://github.com/patacrep/patacrep/blob/f7847d4ab7c977b9a09b87d55eabe21081781710/patacrep/songs/__init__.py#L180) et ses sous classes.

L'objet `config` correspond à la configuration de l'ensemble du carnet. Est-ce pertinent de transmettre *toute* cette configuration à chaque chanson ? Ou peut-on n'en transmettre qu'une partie ?

**Comment by oliverpool** [comment]
J'avoue que j'ai été assez gêné par cet argument assez opaque...
Je suis très favorable à sa suppression en faveurs d'arguments plus explicites!

**Comment by oliverpool** [comment]
#165 a bien fait disparaître l'argument `config` de `_parse`
