### ISSUE TITLE
Renvoyer None en cas de fichier non trouvé

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#104]
Cf https://github.com/patacrep/patanet/commit/cbb19094d0e1bdbbd5c1f429d0979aa8fc436f82

En fait, cela pourrait être gérer dans les templates:

Dans le template Chordpro, si `search_file` renvoie `None`, alors on affiche le nom du fichier.
Dans les templates HTML/LaTeX, on affiche rien.

Exemple: http://stackoverflow.com/a/24385828/3207406

**Comment by paternal** [comment]
J'y avais repensé aussi enter temps.

Pour le comportement.
- En LaTeX, on renvoit le fichier s'il existe. S'il n'existe pas, on n'affiche rien ? On lève une erreur ? On affiche une erreur dans le PDF ? Je dirais : on loggue une erreur, et on n'affiche rien.
- En chordpro, actuellement, pour les tests, j'avais en tête que le rendu soit exactement la même chose que la source (à des espaces et sauts de ligne près). Du coup, je dirais plutôt : `search_file` renvoit son argument, sans traitement.
- En HTML, faites comme vous voulez.

Pour la méthode, j'ai aussi pensé à l'exception `FileNotFoundError`. Je pensais à quelque chose come : par défaut, on lève `FileNotFoundError` si le fichier n'est pas trouvé. Ensuite, on ajoute un argument optionnel `context` à la méthode [`render()`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/__init__.py#L46) : c'est un dictionnaire qui est ajouté au contexte jinja. Chaque format de sortie peut ainsi emballer (« wrap ») la fonction `search_file` dans une autre fonction qui fait ce qu'il faut, à savoir intercepter l'exception `FileNotFoundError` pour en faire ce qu'il veut.

Ça ne doit pas être compliqué à coder ; je pourrai proposer cela, ça sera plus clair que mes explications.

**Comment by oliverpool** [comment]
Est-ce qu'il est nécéssaire d'utiliser `FileNotFoundError` ? `None` n'est pas suffisant ?

Je pense que `None` peut-être plus facilement géré dans les templates qu'une exception (et si celle-ci est nécéssaire, la classe fille peut la générer).

Ou alors on définit `search_file` en privée, avec obligation d'implémenter `search_image` & `search_partition` (qui renvoient `None` ou lèvent une exception

**Comment by oliverpool** [comment]
> En chordpro, actuellement, pour les tests, j'avais en tête que le rendu soit exactement la même chose que la source (à des espaces et sauts de ligne près). Du coup, je dirais plutôt : search_file renvoit son argument, sans traitement.

Dans ce cas, autant afficher directement l'argument, sans utiliser `search_file` (ou `search_partition`)

**Comment by oliverpool** [comment]
Et dans tous les cas, on peut logger une erreur (sans interompre l’exécution), et on laisse le template décider de l'affichage

**Comment by paternal** [comment]
> Dans ce cas, autant afficher directement l'argument, sans utiliser search_file (ou search_partition)

Pas bête. Mais je sesais tout de même d'avis de laisser les `search_*` qui renvoient bêtement leur argument. Comme ça, quelqu'un voulant surclasser la classe pour faire un traitement particulier sur ces fichiers (par exemple vérifier qu'ils existent) aura juste à ré-écrire ces fonctions, mais pas besoin de toucher aux templates.

**Comment by oliverpool** [comment]
> Comme ça, quelqu'un voulant surclasser la classe pour faire un traitement particulier sur ces fichiers (par exemple vérifier qu'ils existent) aura juste à ré-écrire ces fonctions, mais pas besoin de toucher aux templates.

Sinon on pourrait rajouter une méthode `search_result` qui peut être facilement surclassée (et qui est appelée à la fin de `search_file`:
```py
def search_result(file_searched, result):
  return file_searched # pour ChordPro

  return result # pour LaTeX
  return static(..., result) # pour HTML avec patanet
```

**Comment by paternal** [comment]
> Sinon on pourrait rajouter une méthode search_result qui peut être facilement surclassée (et qui est appelée à la fin de search_file:

Pourquoi ne pas surclasser `search_*` directement ?

En chordpro : 
~~~python
def search_image(self, image):
    return image

def search_partition(self, partition):
    return partition
~~~

En LaTeX

~~~python
def search_image(self, image):
    path = super().search_image(image)
    if path is None:
        LOGGER.warning("File not found…")
    return image

def search_partition(self, partition):
    path = super().search_partition(partition)
    if path is None:
        LOGGER.warning("File not found…")
    return partition
~~~

Ou alors, en LaTeX, on renvoit `None` si le fichier n'est pas trouvé, et le template ignore la commande `{image: FOO}` si c'est le cas.

**Comment by oliverpool** [comment]
Effctivement, c'est plus élégant.
On pourrait même surclasser `search_file` directement (à moins de vouloir un traitement différencié pour les partitions et les images, ce qui n'est actuellement pas le cas)

**Comment by oliverpool** [comment]
Le problème, c'est que cela dépend du format de sortie (LaTeX, ChordPro, HTML), et que les méthodes sont liées aux formats d'entrée !

Il faudrait donc déplacer ces méthodes dans d'autres classes (HtmlRender, LatexRenderer, ChordproRendere)

**Comment by paternal** [comment]
> On pourrait même surclasser search_file directement (à moins de vouloir un traitement différencié pour les partitions et les images, ce qui n'est actuellement pas le cas)

Si, c'est le cas : on ajoute un ensemble d'extensions prédéfinies au nom fourni, qui sont différentes pour les images et les partitions.



> Le problème, c'est que cela dépend du format de sortie (LaTeX, ChordPro, HTML), et que les méthodes sont liées aux formats d'entrée !

Effectivement…

> Il faudrait donc déplacer ces méthodes dans d'autres classes (HtmlRender, LatexRenderer, ChordproRenderer)

Oui, ou alors faire le traitement dans les templates… Par exemple en LaTeX (syntaxe approximative) : 
~~~
(* set image=search_image(foo) *)
(* if image is None *)
% Image (( image )) not found
(* else *)
\image{((image))}
(* endif *)
~~~

J'ai peut-être une préférence pour différentes classes suivant le format de sortie… Dans ce cas, il faudrait retravailler les méthodes `render_*()`.

**Comment by oliverpool** [comment]
Je pense que c'est une bonne idée les classes en fonction du format de sortie.

Ca permettra de faire une meilleure séparation entre ce qui concerne la compréhension (parsing) et ce qui concerne le rendu.

**Comment by paternal** [comment]
Du coup, il faut un moyen de définir quelles classes permettent de générer quel format. Actuellement, la variable [`SONG_PARSERS`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/__init__.py#L79-L81) définit les formats d'entrée. En pourrait la transformer en dictionnaire avec les formats de sortie : 

~~~python
SONG_PARSERS = {
   'sgc': {
      'latex': Chordpro2LatexSong,
      'chordpro': Chordpro2ChordproSong,
    },
}
~~~

On pourrait aussi dire que chaque classe définit une liste des formats suportés, d'une manière ou d'une autre. Par exemple, avec un attribut `output_formats`.

Ou alors chaque classe définit une méthode de classe permettant de l'interroger pour savoir si elle permet le rendu vers un format donné. Si `MaClasse.can_render('latex')` vaut `True`, alors on peut générer du LaTeX. L'avantage de cela, c'est que la liste des formats n'est pas définie en dur, mais de manière dynamique. Ainsi, on peut tout de même avoir une classe, qui peut générer tout ce qu'elle veut, en vérifiant à l'exécution qu'elle a les templates pour.

**Comment by oliverpool** [comment]
Ce que j'ai en tête c'est plutôt une classe de rendu par format de sortie, mais je ne sais pas trop si c'est bien faisable.

Le format d'entrée peut être donné dans le constructeur: `LatexRender(chordProSong)`, quitte à ce que les méthodes s'adaptent au format d'entrée.

Avec une classe mère qui implémente les 'search_*`, avec surclassement (surclassage?) des classes filles.

La classe mère peut avoir des méthodes `render_ast` ou `render_as_latex_import` (qui seront appelées en fonction du format d'entrée)

**Comment by paternal** [comment]
> Ce que j'ai en tête c'est plutôt une classe de rendu par format de sortie, mais je ne sais pas trop si c'est bien faisable.

Ça me parait compliqué, dans la mesure où le rendu est intimement lié au format obtenu lors du parsage : ça se voit dans la conversion des fichiers LaTeX et chordpro : dans un cas, on se contente de générer un « lien » vers le fichier LaTeX ; dans l'autre, on produit du code LaTeX. Et l'utilisation de deux fonctions `render` différentes (`render_ast` et `render_as_latex_import`) est dommage car on serait obligé de connaître les entrailles d'une classe pour pouvoir la rendre (alors qu'une méthode `render` agnositque permet d'utiliser les classes en boîte noire, sans savoir comment elles fonctionnent).

Je revois ce que je disais plus haut et propose quelque chose de plus simple : la constante `SONG_PARSERS` est un dictionnaire de dictionnaires de classes du genre de [`Chordpro2HtmlSong`](https://github.com/patacrep/patanet/blob/song_edition/generator/songs.py#L36) de patanet : une classe pour un format d'entrée particulier et un format de sortie particulier. Évidemment, il y a des choses en commun, c'est là que l'héritage entre en jeu. Notre classe [`ChordproSong`](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/__init__.py#L12) reste à peu près la même, et prend en charge le « parsage » et le rendu générique avec des templates, et on écrit plusieurs classes `Chordpro2HtmlSong`, `Chordpro2LatexSong`, `Chordpro2ChordproSong` qui n'ajoutent quasiment rien, si ce n'est définir le format de sortie dans la méthode `render`. Toutes ces classe héritent d'une classe `Song` et doivent implémenter deux méthodes `parse` et `render` (d'ailleurs, il faut que je vois si `parse` ne peux pas disparaitre et être fait dans `__init__`). Enfin, notre constante `SONG_PARSERS` ressemble à : 

~~~python
SONG_PARSERS = {
  'latex': {
    'is': LatexSong,
    'sg': LatexSong,
    'sgc': Chordpro2LatexSong,
  },
  'html': {
    'sgc': Chordpro2HtmlSong,
  },
  'chordpro': {
    'sgc': Chordpro2ChordproSong,
  },
}
~~~

Par exemple `SONG_PARSERS['latex']['sgc'] = Chordpro2LatexSong` signifie : la classe `Chordpro2LatexSong` permet de convertir un fichier source `.sgc` au format `latex`.

Tant qu'on y est, je propose de renommer `SONG_PARSERS` en `SONG_RENDERERS`: ce qui nous intéresse, c'est mettre en forme des chanson (*render songs*) ; le « parsage » n'est qu'un mal nécessaire.

[HS]Je suis crevé ; désolé si ça n'est pas très clair…[/HS]

**Comment by oliverpool** [comment]
Ok je pense comprendre ce que tu veux dire.

En fait, je me dis qu'il y a deux possibilités (en toute généralités) : soit on fait le rendu d'un fichier brut (type LaTeX : on ne parse quasiment rien), soit c'est le rendu d'un fichier "parsé" en AST (actuellement seulement ChordPro, et probablement pas d'autres formats avant un moment).
Si c'est un fichier parsé en AST, tous les "renderers" risquent d'être identiques (ou très similaires).

Du coup en adaptant ta proposition, il suffit de faire une classe `ASTRenderer` dont les classes `ChordPro2*` héritent (avec notamment les méthodes `search_*` qu'elles peuvent surcharger).

Concernant `SONG_PARSERS`, toutes tes proposition me conviennent.
J'en ai une autre : inverser  l'ordre des clés. `SONG_RENDERERS[ext][output]` (je trouve que la lecture est plus naturelle : de `sgc`, vers `latex`. De plus on voit plus rapidement les formats de sortie supportés par un format d'entrée donné.

**Comment by paternal** [comment]
> Du coup en adaptant ta proposition, il suffit de faire une classe ASTRenderer dont les classes ChordPro2* héritent (avec notamment les méthodes search_* qu'elles peuvent surcharger).

J'ai l'impression que ta classe `ASTRenderer` correspond exactement à ma classe `ChordproSong`, non ? Sinon, c'est bon. Je me disais seulement que cette classe est spécifique au parsage du Chordpro, d'où le chordpro dans le nom. Si jamais un jour quelqu'un écrit une classe qui parse un autre format, il y aura un autre parsage, avec un AST différent (ou alors le même, auquel cas il faudra déplacer le module `ast` de `songs.chordpro` dans `songs`). Mais globalement je me fiche de ce nom :stuck_out_tongue: .



> J'en ai une autre : inverser l'ordre des clés. SONG_RENDERERS[ext][output] (je trouve que la lecture est plus naturelle : de sgc, vers latex. De plus on voit plus rapidement les formats de sortie supportés par un format d'entrée donné.

C'était aussi mon idée au départ, je trouve ça aussi plus naturel, puis je me suis dit que pour songbook, on veut rendre du LaTeX, donc on s'intéresse à tout ce qui peut rendre du LaTeX, et on ignore le reste. En mettant le format de sortie en premier, il suffit de considérer `SONG_RENDERERS['latex']` ; si on met le format d'entrée en premier, il faut faire `[SONG_RENDERERS[source]['latex'] for source in SONG_RENDERERS if 'latex' in SONG_RENDERERS[source]]` pour avoir la liste des formats d'entrée disponibles.

**Comment by oliverpool** [comment]
> donc on s'intéresse à tout ce qui peut rendre du LaTeX

C'est pas faux... 
Du coup, autant garder comme c'est.

**Comment by paternal** [comment]
Pour info, je suis en train de bosser là-dessus. Ça n'est pas encore commité car c'est plein de `TODO`, mais ça viendra.

**Comment by oliverpool** [comment]
:+1:
