### ISSUE TITLE
Changement du format de fichier songbook

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#106]
Je n'aime pas écrire des [fichiers de configuration](https://github.com/patacrep/patadata/blob/master/books/naheulbeuk.sb) en json. Pourquoi s'embêter avec ce format rigide, alors que Python sait gérer des fichiers de configuration bien plus ergonomiques (pour les geeks, du moins) avec [`configparser`](https://docs.python.org/3.4/library/configparser.html).

J'ai en tête de faire en sorte que les fichiers songbook soient dans un format reconnu par `configparser`. Pour patanet, je suppose que ça ne change pas grand'chose, si vous n'écrivez pas un tel fichier mais utilisez directement la classe [SongbookBuilder](https://github.com/patacrep/patacrep/blob/master/patacrep/build.py#L134). Pour patagui, le plus simple serait de maintenir la compatibilité json (à moins qu'il y ait des passerelles pas trop complexes pour passer un dictionnaire de strings de Python à C++).

Des commentaires ?

**Comment by LaTruelle** [comment]
Du point de vue patagui, ça ne pose pas de problèmes particulier je pense. Il faudra peut être inclure les librairies boost si QSettings ne suffit pas, mais ce n'est rien de très fou. Par contre, je voudrais bien un example de ce que tu imagines (et pour quel type de fichier tu veux les utiliser) afin que je ne passe pas trop de temps sur du json dans patagui si c'est voué à changer dans un futur proche !

(Je pense typiquement aux templates, tu veux les changer aussi ?)

**Comment by paternal** [comment]
Pour les templates, je ne veux pas les changer (pas pour le moment, du moins ; voir #107).

Pour le reste, mon idée est de transformer un fichier actuel : 

~~~json
{
"template" : "patacrep.tex",
"bookoptions" : [
    "importantdiagramonly",
    "repeatchords",
    "lilypond",
    "pictures"
  ],
"booktype" : "chorded",
"lang" : "french",
"authwords" : {
  "sep" : ["and", "et"]
  },
 "datadir" : ".",
 "content" : [["section", "Traditional"],
                "chevaliers_de_la_table_ronde.sg",
                "greensleeves.sg",
                "vent_frais.sg",
                ["section", "Example"],
                "example-fr.sg",
                "example-en.sg"]
}
~~~

en quelque chose comme ça : 

~~~config
[book]
  template = patacrep.tex
  type = chorded
  lang = french
  datadir = .
  content = [
      ["section", "Traditional"],
      "chevaliers_de_la_table_ronde.sg",
      "greensleeves.sg",
      "vent_frais.sg",
      ["section", "Example"],
      "example-fr.sg",
      "example-en.sg"
      ]

[display]
  diagram = important
  repeatchords
  lilypond
  pictures

[authors]
  separators = and et
  ignore = anonyme anonymous

[titles]
  prefix = The Le Les La À
~~~

Les avantages :

- une structure moins rigide (l'ensemble n'est pas entouré de `{` et `}` ; pas besoin de faire attention aux virgules à la fin des lignes (sauf la dernière), etc.) ;
- une division en section plus claire ;
- l'occasion de revoir le nom ou la forme de certaines options (par exemple, `importantdiagramonly` et `diagram` peuvent devenir `diagram=important`, `diagram=all`, `diagram=none`) ;
- etc.



Actuellement, ce fichier est lu par songbook, transformé en un dictionnaire, et ce dictionnaire est passé comme argument à la classe [`SongbookBuilder`](https://github.com/patacrep/patacrep/blob/master/patacrep/build.py#L134). Je ne sais pas comment tout ça est utilisé par patagui, mais :

- si patagui ne fait qu'écrire un fichier `foo.sb`, et appelle `songbook foo.sb` dessus, pas de problèmes : il faut juste changer la fonction qui écrit le fichier ;
- si patagui appelle en Python la classe `SongbookBuilder`, pas de soucis non plus : le dictionnaire passé en argument ne devrait pas trop changer ;
- si patagui doit lire ce fichier, là, c'est un chouïa plus compliqué, parce que le module [`configparser`](http://docs.python.org/3.4/library/configparser.html) de python fait plein de trucs intéressant (comme des valeurs par défaut et de l'interpolation). Mais on peut aussi dire que patagui ne supporte qu'un sous-ensemble de ce qui est supporté par patacrep.

**Comment by LaTruelle** [comment]
Patagui lit et écrit les fichiers sb, par contre, même si la syntaxe json est très bien gérée en Qt, cela ne veut pas dire quoi ne peut pas utiliser la syntaxe "ini". Et éventuellement, on peut utiliser SongbookBuilder il faut que je me penche là dessus. Cela permet d'être plus souple quand à des changements d'architecture côté patacrep, par contre cela nécessite pas mal de communication entre C++ et python donc à voir.

**Comment by paternal** [comment]
On peut aussi conserver les deux formats : 

- un fichier `book.setup` est analysé avec le nouveau format, dans patacrep uniquement ;
- un fichier `book.json` est analysé avec l'ancien format, dans patacrep, ou dans patagui.

Même si on fait cela, ce sera l'occasion de faire un peu de ménage et réorganisation dans les options, donc je pense que le format du json changera, même si ça restera du json.

**Comment by paternal** [comment]
Nouvelle idée : On peut se passer complètement de l'appel de fonctions Python depuis C++, en écrivant un petit binaire qui lit le fichier au nouveau format, et affiche sur la sortie standard les données converties en Json. Comme ça, tout ce que patagui a à faire, c'est appeler une commande externe (facile), récupérer la sortie (facile, je suppose), et interpréter du json (facile, je suppose).

**Comment by LaTruelle** [comment]
Je suis pas sûr que rajouter des binaires externes qu'il faudra maintenir juste pour patagui ce soit idéal. Il vaut mieux soit intégrer ça à patagui, soit se débrouiller dans patagui pour que les fichiers ini soient lus. En plus, ça doit se faire tout le temps en C++ donc je pense qu'il faut juste trouver la bonne librairie, voire utiliser QSettings qui sait faire ça si ce n'est pas trop sophistiqué. Je vérifierai les limitations connues pour voir si ça risque de poser problème.

**Comment by paternal** [comment]
De toutes manières, il faudra un peu reformater le code Python pour faire une fonction qui produit un dictionnaire (pour que ça soit utilisable par patagui). Afficher ce dictionnaire en json prendrait deux lignes de plus. Donc si tu changes d'avis, pas de soucis : ça sera très vite fait.

Même chose pour les templates…

**Comment by paternal** [comment]
Inclus dans #111.
