### ISSUE TITLE
Utiliser jinja2 pour lire les options des templates

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#107]
Actuellement, pour les [options des templates](https://github.com/patacrep/patacrep/blob/master/patacrep/data/templates/patacrep.tex#L21-L63), on va chercher ces variables à coup de regexp, et on analyse comme du json. Or, il se trouve que jinja permet (1) de définir des variables dans les templates et (2) de charger ces templates et [récupérer la valeur de ces variables](http://jinja.pocoo.org/docs/dev/api/#jinja2.Template.module) dans du code python. Dans l'idée de ne pas réinventer la roue, je pense que ça nous simplifierait la vie.

Pour patacrep, pas de soucis. Pour patanet, pas de problèmes. Reste patagui… 

Je ne sais pas à quel point c'est complexe d'appeler des fonctions Python depuis de C++, mais si ça n'est pas trop complexe, c'est bien : dans ce cas, on peut isoler la fonction qui lit les templates et renvoit les options, et qui sera appelée aussi bien par patacrep (en Python) que par patagui (en C++). Si c'est compliqué, on abandonne… La manière de faire actuelle fonctionne (même si je trouve quand même qu'elle est un peu cracra), donc on ne va pas la casser, d'autant que ces options sont principalement utilisées par patagui.

Par exemple, python documente [cela](https://docs.python.org/3.4/extending/embedding.html), mais je ne sais pas si c'est facile à mettre en œuvre, et utile dans notre cas.

**Comment by LaTruelle** [comment]
De mon point de vue ça ne me paraît pas infaisable, surtout que pour l'instant le support des templates est plus que minimal, je suis d'ailleurs en train de me pencher sur une réécriture de pas mal de code suite à la déprécation de QtScript. Donc autant partir sur quelque chose de plus pratique pour tout le monde.

Appeler des fonctions simples python depuis C++ est relativement simple, il y aura peut être quelques bidouilles à voir sur les types mais rien de très extraordinaire, vu qu'on aura surtout des listes ou des variables diverses.

**Comment by paternal** [comment]
Même commentaire que pour https://github.com/patacrep/patacrep/issues/106#issuecomment-145387807 : On peut se passer d'appeler python depuis C++ en faisant appel à une commande externe écrite en python, qui lit les templates, compile les variables définies dans ces templates, et affiche le résultat comme du json sur la sortie standard. Tout ce que C++ a à faire, c'est appeler la commande, récupérer la sortie, et l'interpréter comme du json.

**Comment by paternal** [comment]
Inclus dans #111.
