### ISSUE TITLE
Amélioration de la gestion des options

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#111]
Pour différentes raisons (ordonner les options, proposer un fichier `.sb` plus clair, définir de manière plus robuste des options dans les templates), je propose la chose suivante. Ce ticket reprend les idées de #107 et #106.

# Nature de la variable d'options

Actuellement, les options sont un dictionnaire, où les clefs sont la référence de l'option, et la valeur sa valeur. C'est le bazar… Je propose de trier les options par section : dans `option['authors']`, on aurait le dictionnaire d'options relatives aux auteurs, etc. Aucun intérêt au niveau du code, mais je pense que le résultat sera plus lisible pour l'utilisateur (voir pour les développeurs).

## Ficher `.sb`

Le format de fichier est analysé par la bibliothèque [`configparser`](https://docs.python.org/3.4/library/configparser.html) (#106). Cela permet, d'une part, de faire un format de fichier plus agréable à écrire pour l'utilisateur (bien moins verbeux que le json, par exemple), et d'autre part, cela permet de trier les options par sections (voir l'exemple en fin de ce commentaire https://github.com/patacrep/patacrep/issues/106#issuecomment-145357963). À l'arrivée, l'objet récupéré est, à peu de choses près, un dictionnaire de dictionnaires.

## Templates

Les templates sont analysés par jinja2 (#107). Cela permet d'avoir quelque chose de plus robuste (actuellement, c'est une série de regexp qui s'en chargent). J'hésite encore entre deux formats de données pour les variables manipulées par jinja2 : soit un dictionnaire de dictionnaire, avec une méthode update intelligente (voir plus bas), ce qui nécessite d'écrire une nouvelle classe ; soit un simple dictionnaire avec des clefs au format `section.option`, qui est ensuite analysé et converti en dictionnaire de dictionnaires. Cela donnerait l'un des formats suivants.

~~~python
(* do options.update({
    'authors.separators': 'and et',
    'book.language': 'french',
  }) *)
~~~

~~~python
(* do options.update({
    'authors': {
      'separators': 'and et',
    },
    'book': {
      'language': 'french',
    },
  }) *)
~~~

On peut aussi imaginer (toujours avec une classe maison ressemblant à un dictionnaire.

~~~python
(* do options.set('authors', 'separators', 'and et') *)
(* do options.set('book', 'language', 'french') *)
~~~

La différence entre les deux formats dépend aussi de la manière dont patagui va gérer cela : dans la première version (un simple dictionnaire), si patagui appelle une fonction python et récupère son résultat, elle récupère un bête dictionnaire de chaînes de caractères, donc c'est simple. S'il s'agit de la deuxième option, elle récupère un objet maison, donc c'est peut-être plus compliqué (rappel : on parle de C++ ici).
Si en revanche, on écrit un petit binaire (comme proposé ici https://github.com/patacrep/patacrep/issues/106#issuecomment-145387807) qui lit les templates et affiche sur la sortie standard un dictionnaire en json, alors on fait ce qu'on veut : patagui n'aura qu'à faire un appel système et lire la sortie, on fait comme on veut à l'intérieur.

### Intérêt d'une méthode `update` plus fine

Si notre dictionnaire de dictionnaires utilise le type `dict` de python, alors on se retrouve avec le problème suivant.

~~~python
d = {
  'foo': {
    'un': 1,
    'deux': 2,
  }
}

d.update({
  'foo': {
    'deux': 22,
    'trois': 3,
  }
})

# Maintenant, d vaut :
# {
#   'foo': {
#     'deux': 22,
#     'trois': 3,
#   }
# }
# alors qu'on voudrait qu'il vaille :
# {
#   'foo': {
#     'un': 1,
#     'deux': 22,
#     'trois': 3,
#   }
# }
~~~

D'où l'intérêt, si c'est pertinent vue l'option choisie pour les templates, d'écrire une version « récursive » de `update()`.

## Assemblage

Ces deux objets (options du fichier `.sb` et des templates) sont ensuite mergées pour obtenir les options du carnet de chant, qui sont ensuite utilisées dans l'ensemble du carnet.

# Traduction des noms de section

Si je me souviens bien, les options des templates sont utilisées par patagui pour construire de manière dynamique des menus de configuration. C'est la raison pour laquelle nous avons, dans les templates, traduit les descriptions des options, et les valeurs par défaut (pour certaines valeurs). Je propose en plus d'ajouter, dans chaque section, de manière optionnelle, la clef `_meta`, qui contient un dictionnaire de la forme : 

~~~python
{
  'title': {
    'french': 'Options des auteurs',
    'english': 'Author options',
  },
  'description': {
    'french: 'Options permettant de définir la manière dont les auteurs sont analysés et triés.',
  },
}
~~~

Cela permet à Patagui de traduire les noms de section, comme elle le faisait avec le nom des options. Ce format est extensible (on peut ajouter des clefs), donc on pourra ajouter encore d'autres choses dans le futur.

# Tri des options

Tout cela serait aussi l'occasion de faire un peu de tri dans les options, de les rassembler en section, voire de modifier le comportement de certaines (ar exemple, `importantdiagramonly` et `diagram` peuvent devenir `diagram=important`, `diagram=all`, `diagram=none`).

---

# À vous !

**Comment by LaTruelle** [comment]
Pour patagui, pythonqt permet assez de souplesse vis à vis des conversions entre types python <-> C++ donc tant qu'une fonction python renvoie un type "standard". Pour plus d'infos, voir le premier tableau [ici](http://pythonqt.sourceforge.net/Developer.html). Il faut par contre éviter les objets trop sophistiqués je pense, mais des strings et associés ne poseront pas de problème.

**Comment by paternal** [comment]
Du coup, je pense que pour les templates, le plus simple pour les deux parties (patacrep et patagui) est de faire un objet maison (un dictionnaire de dictionnaire avec une méthode `update` intelligente, comme décrit plus haut), et lui fournir une méthode `__dict__()` pertinente.

Comme ça, de ton côté, au lieu d'appeler quelque chose comme `SongbookTemplates.get_options()`, tu appelerais `vars(SongbookTemplates.get_options())`, et tu récupèrerais un dictionnaire de dictionnaires de `str`, les clefs étant des `str` également.

**Comment by oliverpool** [comment]
Je ne pense pas être très concernée par la partie technique : je vous laisse décider.

Je suis très favorable à un ménage/tri des options !

**Comment by paternal** [comment]
Le changement est tout de même important dans la mesure où il n'est pas rétro-compatible (et [ce n'est pas le seul](https://github.com/patacrep/patacrep/labels/backward%20incompatible)).

**Comment by paternal** [comment]
Proposition de réorganisation et tri des options : https://github.com/patacrep/patadata/wiki/Options

**Comment by oliverpool** [comment]
> https://github.com/patacrep/patadata/wiki/Options. À vos claviers pour améliorer cela !

L'état actuel me plaît déjà bien!.

Il y a beaucoup d'options qui concerne juste les carnets avec accords (majoritairement dans `display`).
Du coup je propose de la renommer en `chords` et que `book` contienne les autres options:
* book : L'idée est qu'on puisse définir un carnet fonctionnel juste avec cette section (c'est la raison pour laquelle `template` est ici et non pas dans la section `latex`).
    * template: STRING
    * lang: STRING
    * datadir: LISTE
    * content: STRING interprétée en JSON
    * encoding: STRING
    * pictures: BOOLEAN
* chords : Pour les musiciens
    * display: BOOLEAN (anciennement `booktype=chorded` ou `booktype=lyrics`)
    * notation: ENUM[english, latin] : [plus logique je pense](https://fr.wikipedia.org/wiki/Histoire_de_la_notation_musicale)
    * diagram**page**: BOOLEAN (pour ajouter la double page d'accord en début de carnet)
    * diagram**reminder** : ENUM[important, none, all] \(anciennement `importantdiagramonly`)
    * repeatchords: BOOLEAN
    * lilypond: BOOLEAN
    * instruments: LISTE[guitar, ukulele]

Et du coup, je suppose qu'il y aura des valeurs par défaut?

Sachant que l'option `content` risque d'être assez longue, est-ce que ça vaudrait pas le coup d'en faire une section indépendante ?

**Comment by paternal** [comment]
J'ai déplacé ça dans le wiki de patacrep (je me suis planté et j'avais mis ça dans patadata). Toutes tes propositions me conviennent.

https://github.com/patacrep/patacrep/wiki/Options

**Comment by paternal** [comment]
Pour l'option `notation`, est-ce que `letter` et `solfege` ne conviendraient pas mieux ?
https://en.wikipedia.org/wiki/Musical_notation#Other_systems_and_practices

**Comment by oliverpool** [comment]
J'ai l'impression qu'il existe beaucoup de notations différentes, par exemple :
* les allemands utilisent le `H` à la place de `B` (dans la notation anglophone)
* l'accent aigu du Ré est seulement utilisé en français (et pas en italien notamment)

**Comment by paternal** [comment]
On peut peut-être du coup ajouter une option `notenames`. L'option `notation=french` ne serait qu'un raccourci pour `notenames=Do Ré Mi Fa Sol La Si`, tout comme `notation=english`.

**Comment by oliverpool** [comment]
Ca serait parfait!

**Comment by oliverpool** [comment]
Avec priorité pour `notenames`, si celui-ci est défini (`notation` est alors simplement ignoré)

**Comment by paternal** [comment]
Pour info, pour simplifier la [gestion des traductions](https://github.com/patacrep/patacrep/blob/205c6c3c6590a2f6fe975ab0b9f934db22db9d3c/patacrep/data/templates/songs.tex#L34-L40), je pense utiliser [`gettext`](https://docs.python.org/3/library/gettext.html) : pas la peine de réinventer la roue.

**Comment by oliverpool** [comment]
> utiliser [`gettext`](https://docs.python.org/3/library/gettext.html) 

Si j'ai bien saisi le fonctionnement: 
* on écrit tout dans une langue (en indiquant qu'elles sont à traduire)
* puis on liste ces phrases et on les traduit (avec le logiciel qui va bien)

Questions:
* quelle langue principale utiliser ? (je suis favorable à l'anglais)
* est-ce que ces traductions seront stockées dans le package ou aussi dans le datadir (je pense que les stocker dans le datadir rajoute beaucoup de complexité pour un gain assez faible)

**Comment by paternal** [comment]
> Si j'ai bien saisi le fonctionnement:
> 
>    * on écrit tout dans une langue (en indiquant qu'elles sont à traduire)
>    * puis on liste ces phrases et on les traduit (avec le logiciel qui va bien)

C'est ça. C'est un outils standard, qui a son équivalent dans tous les langage. Si tu veux voir ce que ça donne en action, il y a par exemple [ce tutorial](http://inventwithpython.com/blog/2014/12/20/translate-your-python-3-program-with-the-gettext-module/). Et j'ai regardé vite fait, mais normalement, on aura pas de soucis à faire fonctionner ça avec jinja2.

> quelle langue principale utiliser ? (je suis favorable à l'anglais)

:+1:

> est-ce que ces traductions seront stockées dans le package ou aussi dans le datadir (je pense que les stocker dans le datadir rajoute beaucoup de complexité pour un gain assez faible)

:+1: pour les mêmes raisons.

**Comment by oliverpool** [comment]
> Si tu veux voir ce que ça donne en action

On l'utilise déjà dans patanet :stuck_out_tongue:

**Comment by oliverpool** [comment]
Est-ce qu'on en profite pour changer l'extension en "*.ini" pour que la coloration syntaxique soit automatique ?

**Comment by oliverpool** [comment]
On pourrait aussi autoriser un fichier `default_config.ini` dans le datadir, pour spécifier automatiquement des valeurs par défaut (avec des `updates` en chaîne - celui de l'utilisateur étant en dernier)

**Comment by paternal** [comment]
> Est-ce qu'on en profite pour changer l'extension en *.ini pour que la coloration syntaxique soit automatique ?

Je suis partagé : j'aime bien `.sb` (plus précis que `.ini`), mais la coloration syntaxique qui fonctionne toute seule, c'est bien aussi…

Après, le seul endroit où cette extension apparait (hors des commentaires), c'est pour [compléter une extension manquante](https://github.com/patacrep/patacrep/blob/master/patacrep/songbook/__main__.py#L131-L132). Donc c'est principalement dans la doc qu'on va conseiller .ini ou .sb.

Bref, tout ça pour dire que je n'en sais rien…

**Comment by oliverpool** [comment]
>  Donc c'est principalement dans la doc qu'on va conseiller .ini ou .sb

Ou `.yml` ;-)
Je suis assez favorable à conseiller `.yml`, car la coloration syntaxique native est quand même très pratique

**Comment by paternal** [comment]
> Ou .yml ;-)
> Je suis assez favorable à conseiller .yml, car la coloration syntaxique native est quand même très pratique

Ok (mais je risque d'oublier : n'hésite pas à me le rappeler quand je proposerai une PR).
