### ISSUE TITLE
Revoir le nom des extensions

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#114]
Il me semble qu'on en avait déjà parlé, mais je n'arrive pas à remettre la main dessus, donc je relance la discussion ici (et désolé si je rouvre une discussion déjà close).

Je ne sais pas ce qu'il en est de votre côté, mais je n'arrive jamais à me souvenir du nom des extensions. Si même les (un des) développeurs ne s'en sortent pas, c'est peut-être que ces extensions ne sont pas bien choisies. Je propose donc les nouvelles extensions suivantes (qui sont logique pour moi ; on verra si elles le sont pour vois) : 
* `csg` : Chordpro song ;
* `tsg` : (La)Tex song ;
* `tis` : (La)Tex inter song ;
* `tex` : fichier LaTeX brut (utilisable par le plugin [`tex`](https://github.com/patacrep/patacrep/blob/master/patacrep/content/tex.py)).

**Comment by Luthaf** [comment]
Ça ne me pose pas forcément de problème. Vu le nombre d'utilisateurs actuels de la version 4.0.0, on peut se permettre des changements non-rétrocompatibles.

**Comment by oliverpool** [comment]
Ca me convient aussi.

**Comment by paternal** [comment]
Ajouté à ma todo liste.

**Comment by paternal** [comment]
> Ça ne me pose pas forcément de problème. Vu le nombre d'utilisateurs actuels de la version 4.0.0, on peut se permettre des changements non-rétrocompatibles.

Du coup, on part sur une version 5 ?

**Comment by oliverpool** [comment]
> Du coup, on part sur une version 5 ?

Ca me va.
Du coup tu créé une branche 5beta ou directement sur master ? 
Pour les issues concernées, on peut donc faire une "milestone"

**Comment by paternal** [comment]
> Du coup tu créé une branche 5beta ou directement sur master ?

Je ne sais pas ce qui est le mieux. Vu que je ne pense pas qu'on ait besoin de maintenir une version 4 en parallèle, je pense qu'on peut faire les modifications dans master directement.

**Comment by oliverpool** [comment]
Après réflexion, cette une nouvelle extension n'est pas forcément très standard:
> Data files that contain ChordPro data are usually given a file name extension **.cho**. Other often used extensions are **.crd**, **.chordpro**, and **.chopro**. [(source)](http://www.vromans.org/johan/projects/Chordii/chordpro/)

Mais d'un autre côté, notre support de chordpro n'est pas non plus standard. Comme dans ce logiciel où ils ont créer `.gcp`, avec directives personnalisées:
> You can use any extension from the list above, but we strongly recommend you to use the .gcp [(source)](http://www.845tools.com/blog/index.php/2012/10/11/introducing-the-new-chordpro-viewer-in-guitartapp/)

Je propose qu'on supporte `.cho`, `.chordpro` et `.csg` en entrée (et que dans patadata on utilise `.csg`)

---

Concernant le `.sg`, je n'ai trouvé aucune référence, donc pas d'opposition à `.tsg`

**Comment by paternal** [comment]
Merci ! Je n'avais pas réussi à trouver de convention pour le nom de l'extension du chordpro !

* chordpro : .cho, .chordpro, .csg
* latex : .tsg
* inter song : .tis
* latex brut : .tex


Vu que ça devrait modifier de petites choses un peu partout, j'attends un moment où on n'a pas douze pull-requests actives pour faire ça.

**Comment by oliverpool** [comment]
> j'attends un moment où on n'a pas douze pull-requests actives pour faire ça

De mon côté, ce n'est pas pressé (je suis presque prêt à attendre la conversion de patadata)

**Comment by oliverpool** [comment]
Ca pourrait être pas mal d'en profiter pour renommer les fichiers `.source` (en `.csg.source` par exemple). Outre la clarification, cela ouvre la porte à tester les fichiers `.tsg.source`.

**Comment by oliverpool** [comment]
Du coup pour les templates tex, on garde l'extension .tex ?

**Comment by oliverpool** [comment]
*je suis chaud pour m'attaquer à ce ticket, une fois que #169 & #172 sont réglées*

**Comment by paternal** [comment]
> Ca pourrait être pas mal d'en profiter pour renommer les fichiers .source (en .csg.source par exemple). Outre la clarification, cela ouvre la porte à tester les fichiers .tsg.source.

Ok.



> Du coup pour les templates tex, on garde l'extension .tex ?

C'est du latex brut (pas forcément des chansons), donc c'est bien de garder tex.

> je suis chaud pour m'attaquer à ce ticket, une fois que #169 & #172 sont réglées

Fonce !
