### ISSUE TITLE
Faire renvoyer à `search_*` des chemins relatifs aux datadirs

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#115]
À résoudre après #104.

Actuellement, on fait tout en sorte pour que LaTeX puisse aller chercher les images dans les datadirs (notamment avec l'utilisation de `graphicspath{{DATADIR1/img}{DATADIR2/img}}`).
Pourtant, les chemins vers les images et partitions contiennent les chemins absolus.

On peut se limiter à mettre des chemins relatifs aux datadirs.

**Comment by oliverpool** [comment]
Du coup, cela veut dire que les ressources (images, partitions...) des chants doivent se trouver dans le même datadir que le chant ?

Certes, cela simplifie le partage de datadir (qui est alors "self-contained"), mais peut provoquer de la duplication de contenu (ce qui me dérange assez peu).

**Comment by paternal** [comment]
Non : ils peuvent être dans n'importe quel datavir, ou dans le même dossier que le chant.

**Comment by paternal** [comment]
En fait, ça marche bien pour tout (datadirs et même dossier que la chanson, latex ou chordpro), sauf dans le cas suivant : un fichier inclus par une chanson chordpro dans le même dossier que celle-ci.

C'est dommage, mais je ne vois pas de solution simple et propre pour résoudre cela.
