### ISSUE TITLE
Déplacer le dossier `examples` ?

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#116]
Y a-t-il une raison pour que le dossier [`examples`](https://github.com/patacrep/patacrep/tree/master/patacrep/data/examples) soit situé dans `patacrep` (et donc installé avec l'application) et non pas dans un dossier `/examples` à la racine ? Si non, je déplace.

**Comment by LaTruelle** [comment]
De mon côté je n'en vois pas, je pense que c'est plus historique comme raison, du temps d'avant la séparation patacrep/patadata.

**Comment by oliverpool** [comment]
Pas d'objection non plus
