### ISSUE TITLE
Analyse des accords dans les {echo}

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#119]
*Problème similaire à #87 (et connecté à https://github.com/patacrep/patadata/issues/23 & https://github.com/patacrep/patadata/issues/24)*

Il s'agit donc de la gestion des accords dans les `echo` ([exemple](https://github.com/patacrep/patadata/blob/master/songs/le_donjon_de_naheulbeuk/maitre_du_donjon.sg#L86))

> @paternal Autoriser les accords dans les directives comment ne me semble pas trivial (j'ai déjà essayé). 

Donc je suppose que dans une directive `echo`, ce n'est pas plus facile.

D'après mes recherche, aucun logiciel disponible actuellement ne supporte une directive similaire, donc on est assez libre sur ce point.

Je propose donc créer une paire de balises `{start_echo}`, `{end_echo}`.
J'ai volontairement omis le `of`, car ce sont des balises `inline` qui ne génèrent pas de nouveaux blocs - à la différence de `verse`, `chorus`, `bridge`.

**Comment by paternal** [comment]
> J'ai volontairement omis le of, car ce sont des balises inline qui ne génèrent pas de nouveaux blocs - à la différence de verse, chorus, bridge.

Il faut que je vérifie, mais je ne sais pas si c'est simple à implémenter, un couple de balises qui ne sont pas un bloc…

Il faut que j'étudie cela…

**Comment by oliverpool** [comment]
> je ne sais pas si c'est simple à implémenter

Peut-être que c'est plus facile "à la main", en considérant séparément les balises `{start_echo}` et `{start_echo}` et en rajoutant un peu de logique pour s'assurer de la cohérence (pas d'imbrication possible, et fermeture obligatoire avant la fin du paragraphe)

Ca rajouterait deux templates pour le début et la fin de l'écho (ce qui n'est pas gênant si la cohérence a été vérifiée en amont)
