### ISSUE TITLE
Gestion des erreurs de compilation

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#121]
Est-ce qu'il serait utile à Patanet de conserver quelque part la liste d'erreurs de compilation de chaque chanson ? Je pense par exemple à un attribut `Song.errors`, qui serait un dictionnaire, avec :

- `Songs.errors['parser']` qui soit une liste de tuples `(ligne, colonne, message)` pour les erreurs de syntaxe ;
- `Songs.errors['files']` qui soit une liste de tuples `(line, name, extension, directories)` pour les fichiers non trouvés (images par exemple) ;
- `Songs.errors['lang']` une liste de tuples `(line, language1, language2)` signifiant : `language1` n'a pas été trouvé, et a été remplacé par `language2`.
- les autres valeurs du dictionnaire n'étant pas encore utilisées, mais laissées pour pouvoir étendre les erreurs gérées plus tard.

**Comment by oliverpool** [comment]
Oui, c'est intéressant à avoir (lors de la modification des chants, pour éviter d'enregistrer un chant qui aurait des erreurs).

Par ailleurs je pourrai m'en servir pour vérifier que la conversation est totalement supportée par patacrep.

Je ne sais pas si tu veux dire quelque chose de particulier avec "conserver" : pour moi "avoir" est suffisant

**Comment by paternal** [comment]
> Je ne sais pas si tu veux dire quelque chose de particulier avec "conserver" : pour moi "avoir" est suffisant

Juste « avoir », pour que patanet puisse afficher à l'utilisateur la liste des erreurs de syntaxe facilement, plutôt qu'en analysant les logs pour récupérer cette information.

**Comment by oliverpool** [comment]
:+1:

**Comment by paternal** [comment]
J'ai édité le message original pour ajouter des erreurs de fichier

**Comment by oliverpool** [comment]
Pour `files` et `lang`, si on peut rajouter le numéro de ligne, ça pourrait être assez pratique (mais j'ai peur que ce ne soit pas évident, à moins que cette vérification soit faite lors du *parsing*).

---

Pour le développement de patanet, je suis actuellement bloqué par cet aspect.
Je compte donc m'y attaquer sous peu dans #172.

Des remarques/recommandations particulières ?

**Comment by paternal** [comment]
Il faut que je vérifie, mais je pense que ça ne doit pas être trop compliqué d'ajouter comme attribut de chaque élément de l'AST la ligne et la colonne à laquelle il apparait (ou du début ou de la fin pour les environnements).

**Comment by paternal** [comment]
C'est à moitié testé, mais ça devrait ajouter un attribut `lineno` aux objets `AST`.
