### ISSUE TITLE
Arrêter la compilation en cas d'erreur

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#123]
Actuellement, les erreurs de syntaxe et les erreurs de fichiers non trouvés sont ignorés silencieusement. Pourquoi pas, mais il faudrait une option (pour laquelle je n'arrive pas à trouver un nom maintenant) qui corresponde au `-Werror` de gcc, et qui permette de dire à `songbook` d'arrêter la compilation (avec un code de retour non nul) en cas d'erreur de syntaxe.

- [x] Transformer les erreurs de compilation en warning (`logging.warning()`) ;
- [ ] Ajouter l'option

**Comment by oliverpool** [comment]
Je pense que c'est un bonne idée.

En revanche pour les interfaces en python (patanet par exemple), est-ce que les exception natives ne sont pas plus facile à gérer ?

**Comment by paternal** [comment]
Je ne savais pas encore comment j'allais gérer ça au moment ou je proposais cela : en gros, à la fin de la génération du .tex, je comptais passer en revue tous les `.errors` des chansons. Si l'un d'eux était non vide, on `sys.exit(1)`.

Si c'est utile pour d'autres projets (ce que tu sembles dire), ça peut se faire dans le builder (à la fin du « step » correspondant), et lever une exception en cas de problèmes. `Songbook` récupèrerait cette exception pour afficher un message propre.

**Comment by LaTruelle** [comment]
Pour patagui ce serait pas mal aussi de pouvoir récupérer les erreurs proprement. Pour l'interface proprement dite ce sera a voir, mais ça permettrait d'utiliser de façon beaucoup plus intense et efficace patacrep.

**Comment by paternal** [comment]
Du coup, on peut se contraindre à ce que l'attribut `.errors` de songs ne soit composé que de types « de base » (dict, str, list, tuple, int) afin de faciliter le traitement par du C++.

Ensuite, pour patacrep, il faudra compiler l'ensemble des `.errors`, donc on pourra en faire une fonction utilisable par patagui.
