### ISSUE TITLE
Caractères spéciaux LaTeX dans chordpro

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#133]
Il y a [apparemment](http://tex.stackexchange.com/a/34586) dix caractères spéciaux en LaTeX:

`& % $ # _ { } ~ ^ \`

Que fait-on lorsque ceux-ci sont trouvés dans un fichier chordpro?

## Présence actuelle dans patadata

* `&`: est parfois présent dans les noms d'artiste, album ou titre (Simon & Garfunkel) et à l'intérieur des `define`, voir https://github.com/patacrep/patadata/issues/27. Actuellement non trouvé dans les couplets.
* `%`: est présent dans les noms d'album ("0% de matière grise" de Johk) et dans quelques couplets
* `$`: était présent pour définir des formules assez simples ($5m^2$, $H_2O$)
* `#`: en dehors des accords, il n'est (actuellement) utilisé que pour les commentaires chordpro
* `_{}`: ne semblent utilisés que pour les directives chordpro (et les noms de fichier pour `_`)
* `~`: est déjà bien traité (espace insécable)
* `^`: a une signification particulière pour le paquet song (répéter un accord)
* `\`: non utilisé (hormis dans les commentaires)

## Proposition de traitement

Échapper automatiquement dans les couplets et champs texte (artiste, titre, album), autorisés dans certaines directives (url par exemple):
* `&`
* `%`

Simplement interdits:
* `\`
* `_` (hors nom de fichier ou url)
* `{`
* `}`
* `$` (pour H2O, je trouve plus lisible sans "2" en indice / 5m² peut utiliser l'UTF-8)

Aucun traitement:
* `#` *marque le début d'un commentaire chordpo, ignoré à la compilation*
* `~` *espace insécable*
* `^` *répétition d'accord*

**Comment by Luthaf** [comment]
Ça me paraît pas mal comme comportement.

**Comment by paternal** [comment]
> $ (pour H2O, je trouve plus lisible sans "2" en indice / 5m² peut utiliser l'UTF-8)

Pour H₂O aussi on peut utiliser l'UTF8. J'ai commencé à regarder un peu xelatex et lualatex (qui sont sensés gérer l'UTF8 mieux que pdflatex), mais à première vue, xelatex ne fonctionne pas avec patacrep, et lualatex ne gère pas correctement nativement `₂` et ` ` (espace insécable). À creuser pourquoi pas.

Je me dis aussi qu'avec LuaLaTeX, les trucs un peu techniques (conversion des images et partitions, mise en cache des partitions compilées #63, etc.) peuvent peut-être faits plus facilement en Lua (jamais testé, je ne fais que supposer).

> `^` répétition d'accord

C'est-à-dire, aucun traitement ? C'est un pourtant un caractère réservé (accepté en math pour indiquer l'exposant).

**Comment by oliverpool** [comment]
> `^` répétition d'accord

J'ai dû mal m'exprimer.
D'après ce que j'ai compris, le package song le redéfini pour répéter les accords (exemple: http://tex.stackexchange.com/q/19813)

Du coup je suis favorable à le laisser tel quel (càd d'offrir cette fonctionnalité à Chordpro)

**Comment by paternal** [comment]
> D'après ce que j'ai compris, le package song le redéfini pour répéter les accords

D'accord. Ça devrait fonctionner sans problèmes alors.

**Comment by paternal** [comment]
> lualatex ne gère pas correctement nativement ₂ et   (espace insécable). À creuser pourquoi pas.

En fait, avec `\usepackage{fontspec}`, ça marche pour ² et l'espace insécable, mais pas pour ₂.

**Comment by paternal** [comment]
Essais avec lualatex : #135.

**Comment by paternal** [comment]
> En fait, avec \usepackage{fontspec}, ça marche pour ² et l'espace insécable, mais pas pour ₂.

On peut ajouter des caractères manquants avec le paquet `newunicodechar`:

~~~latex
\documentclass{standalone}
\usepackage{fontspec}
\usepackage{newunicodechar}
\newunicodechar{₂}{\ensuremath{_2}}
\begin{document}
H₂O
\end{document}
~~~

Du coup, si ça vous va, il reste à faire :

- Correctement traiter `&` et `%` (échapper sauf dans les URL et les accords) ;
- Ajouter le paquet `newunicodechar`.

Correct ?

**Comment by paternal** [comment]
Sans réponse de votre part, un jour, je mettrai mon dernier commentaire en œuvre.

**Comment by oliverpool** [comment]
Ca me va !
