### ISSUE TITLE
Run automic tests under windows

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#137]
Actuellement Travis ne supporte que linux (ubuntu precise).

Je pense qu'il serait bon de tester aussi automatiquement sous windows.
J'ai trouvé un équivalent: http://www.appveyor.com/ (gratuit pour les projets open-source), mais il faut voir si l'installation de latex ne pose pas de soucis (sinon on fait comme travis, on "skip" les tests de compilation)

**Comment by Luthaf** [comment]
> Actuellement Travis ne supporte que linux (ubuntu precise).

OS X aussi ! Cf https://github.com/chemfiles/chemfiles/blob/f65680dd4698cc37d0b61baf83dca7a06bc951af/.travis.yml#L3-L5

**Comment by oliverpool** [comment]
Au temps pour moi.

Ça peut faire l'objet d'un autre ticket et après on devrait être assez blindé aux niveaux tests :smile:

**Comment by Luthaf** [comment]
Ça peut être intéressant d'avoir les 3 plateformes pour vérifier que les instructions d'installation sont toujours à jours.

**Comment by paternal** [comment]
J'ai l'impression qu'on peut fermer, vu que #149 l'a été ?

**Comment by oliverpool** [comment]
Très juste
