### ISSUE TITLE
Comment organiser les données de Patacrep ?

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#150]
Suite de la discussion de 356aa455b5fdcc2c047da15d4be62ac84a07d54d.

**Comment by paternal** [comment]
> > D'autant qu'actuellement, dans master, patacrep/data est un datadir (au sens songbook).
> 
> C'est aspect est très intéressant et peu justement permettre une grande personnalisation: avec un système de liste (ordonnée) de datadir. Pour tout ce qui est type 'data', `patacrep` cherche successivement les datadir jusqu'à trouver le fichier requis (jinja est capable de le faire nativement).
> Pour les utilisateurs avertis ça me semble assez puissant: il suffit de créer un dossier `my_datatir` et de personnaliser justes certains fichiers (templates jinja/templates tex/images html...).

C'est déjà le cas, dans la mesure où [`__DATADIR__` est ajouté](https://github.com/patacrep/patacrep/blob/085442b5835cb13b740889126d3897514abdb31b/patacrep/build.py#L74) à la fin de la liste des datadirs définie par l'utilisateur dans le fichier `.sb`. Comme ça, il sert de datadir par défaut, si rien n'a été trouvé dans les autres. De même pour [la génération des chansons](https://github.com/patacrep/patacrep/blob/085442b5835cb13b740889126d3897514abdb31b/patacrep/songs/chordpro/__init__.py#L51-L58).

> Proposition: création d'un dossier `internal` (ou `patacrep` ou `resources` ou `internal_resources` ou `tex_generation` ou ...) dans le dossier `data` et de regrouper tout ce "bazar" dans des sous-dossiers (si possible bien rangé).

Je ne comprends pas ce que tu appel « tout ce "bazar" ». Tous les dossiers actuels de data ? Juste `ast_chordpro` ?

**Comment by oliverpool** [comment]
> Je ne comprends pas ce que tu appel « tout ce "bazar" ». 

Je pensais à:
>  les dossiers `ast_templates img ast_html_img content_song_templates`.

-

> De même pour [la génération des chansons](https://github.com/patacrep/patacrep/blob/085442b5835cb13b740889126d3897514abdb31b/patacrep/songs/chordpro/__init__.py#L51-L58).

Simplement renommer `data/ast_templates/chordpro` en `data/templates/chordpro` me conviendrait totalement !

 ```py
pkg_datapath('templates', 'chordpro', self.output_language)
```


---

Et on pourrait en profiter pour utiliser la [même astuce](https://github.com/patacrep/patacrep/commit/92b7185a7fa59ef86a9f21273f02636af594d355#diff-df96a6b8812d2ddfeadc37310f536382R20) pour `get_datadirs`:
```py
def get_datadirs(self, *subdir):
```

**Comment by oliverpool** [comment]
Pour mieux gérer l'[inclusion](https://github.com/patacrep/patacrep/blob/master/setup.py#L24-L28), on pourrait simplement rajouter des extensions (.csg, .hmtl, .tsg) aux templates.

Il suffirait alors d'inclure `data/*.*'` il me semble

**Comment by oliverpool** [comment]
Maintenant que #156 est mergé, je propose de repartir sur une nouvelle discussion.
