### ISSUE TITLE
Améliorer l'intégration des données dans le paquet Python

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#151]
Suite de la discussion de https://github.com/patacrep/patacrep/pull/144/files#r43545479. L'idéal serait de faire fonctionner `include_package_data=True` sous Windows.

**Comment by oliverpool** [comment]
En fait ça devrait fonctionner tel quel.

J'ai eu des soucis au début car j'avais déplacer les fichiers sans les ajouter dans git, du coup les tests unitaires plantaient. Mais maintenant qu'ils sont dans le "VCS", ça devrait fonctionner.

**Comment by oliverpool** [comment]
Proposition de résolution dans #156 : https://github.com/patacrep/patacrep/commit/efb36b38152a86137ec39a7b32edb375605f4e90

**Comment by oliverpool** [comment]
@paternal : tu préfères garder cette issue ouverte (pour éventuellement trouver une solution élégante) ou la résolution apportée par #156 est suffisante ?

**Comment by paternal** [comment]
J'ai une nouvelle idée en tête. Je propose une pull-request à l'occasion…
