### ISSUE TITLE
Corriger un problème d'encodage dans les tests

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#155]
Voir https://github.com/patacrep/patacrep/pull/153#issuecomment-153627762

**Comment by oliverpool** [comment]
C'est dû au paquet `chardet`.
Peut-être faut-il essayer de le remplacer par une autre librairie ([fastchardet](https://pypi.python.org/pypi/fastchardet/0.2.0) par exemple se limite aux encodages les plus courants)

**Comment by paternal** [comment]
> Est-ce qu'il serait déraisonnable de considérer tous les chants comme de l'UTF-8 ?

On a déjà passé tellement de temps là-dessus sans trouver de solution efficace que je crois que je suis pour… Ou tout du moins, considérer que tous les chants sont encodés avec l'option `encoding` du fichiers `.sb`.

**Comment by oliverpool** [comment]
Proposition de solution dans #161
