### ISSUE TITLE
Line ending issue

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#157]
*Note pour moi-même*

Sur un système windows, il y a des problèmes de retour à la ligne.
Remplacer https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/lexer.py#L93 par : `r'(\r?\n)|\r'`

**Comment by oliverpool** [comment]
Et modifier multilineEqual:

    def assertMultiLineEqual(self, first, second, *args, **kwargs):
        return super().assertMultiLineEqual(
            first.replace('\r\n', '\n'),
            second.replace('\r\n', '\n'),
            *args,
            **kwargs
        )

**Comment by paternal** [comment]
Je ne comprends pas pourquoi ce bug ne fait pas échouer les tests sous Windows (appveyor). Tu m'éclaires ?

**Comment by oliverpool** [comment]
Le clonage du dépôt git sous AppVeyor ne modifie pas les fins de ligne (donc reste `\n` et les tests se déroulent bien).

J'ai essayé de modifier les fichiers `.source` sous un système windows (ce qui a changé les fins de ligne en `\r\n`) et des tests ne fonctionnent plus (boucle infinie).

Le "vrai" bug est en fait là : https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/lexer.py#L104.

Proposition de correction dans la branche [line_endings](https://github.com/patacrep/patacrep/compare/line_endings)

**Comment by oliverpool** [comment]
Le `assertMultiLineEqual` n'est utile que pour les tests (qui fonctionnent déjà sous AppVeyor), donc pas forcément nécessaires.

**Comment by oliverpool** [comment]
*Suite dans #160*
