### ISSUE TITLE
Suppression d'un dossier obsolète ?

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#159]
Le fichier [install.bat](https://github.com/patacrep/patacrep/blob/061411e3ae87fcd8f7ab23a4835678824d20216a/windows/install.bat) est obsolète. Est-ce que tout le dossier [windows](https://github.com/patacrep/patacrep/tree/061411e3ae87fcd8f7ab23a4835678824d20216a/windows) l'est aussi ?

Il faut soit les mettre à jour, soit les supprimer.

Vu qu'on réussit à installer patacrep sur appveyor sans ces fichiers, je pense qu'on peut tout supprimer.

**Comment by oliverpool** [comment]
Ça dépend des instructions d'installation que l'on veut donner pour windows, mais je suis aussi assez favorable à sa suppression.
