### ISSUE TITLE
Requirements.txt seems deprecated

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#162]
Pour le développement, la commande [`python3 setup.py develop`](https://github.com/patacrep/patacrep/blob/master/README.rst#for-developement) se charge d'installer les dépendances de manière automatique.

Il faudrait donc mettre à jour le README et potentiellement supprimer le fichier `Requirements.txt` (sauf si il y a des dépendances uniquement utiles pour le dev, ce qui n'est pas le cas à l'heure actuelle)

Pour la gestion fine des versions des dépendances, on peut mettre à jour le script de setup: http://python-packaging-user-guide.readthedocs.org/en/latest/requirements/#id5

**Comment by paternal** [comment]
Ou remplacer le contenu de `requirements.txt` par : 
~~~
-e .
~~~

Source : https://caremad.io/2013/07/setup-vs-requirement/

**Comment by oliverpool** [comment]
:+1:

Ça me convient parfaitement !
