### ISSUE TITLE
Organisation des données de Patacrep

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#164]
*Suite de #150 (donc suite de 356aa455b5fdcc2c047da15d4be62ac84a07d54d par transitivité)*

Depuis #156, les données de patacrep sont dans le sous-dossier `data`.
Peut-être que l'arborescence de ce dossier est à retravailler ?
Actuellement:
```py
img/
latex/
templates/
  *.tex
  songs/
```

Je propose cela:
```py
includes/
  img/
  latex/ # pour la licence par exemple (ou les pages de couverture)
  scores/ # pour les partitions lilypond
python/ # pour les plugins (actuellement seulement `content`)
songs/
styles/ # anciennement /latex

templates/
  songbook/ # y déplacer les fichiers *.tex 
  songs/
```
Je pense qu'il serait pas mal de refactoriser les templates .tex ou les renommer, car je ne trouve pas évident que : `patacrep < default < songs < layout` (lire patacrep *extends* default ...)

**Comment by paternal** [comment]
Pour l'organisation des répertoires, ça me va. Il manque juste les partitions (`/includes/scores`) et les modules python (`/python`).

Pour les noms des templates, qu'est-ce que tu proposes ?

**Comment by oliverpool** [comment]
> les modules python (`/python`).

Ceux qui sont dans `content` actuellement ? C'est une bonne idée, j'ai mis à jour mon message en conséquence.

> Pour les noms des templates, qu'est-ce que tu proposes ?

Est-ce qu'il serait possible de les organiser en fonction des catégories des options ? (https://github.com/patacrep/patacrep/wiki/Options)
Plutôt que d'hériter en chaînes, est-ce qu'il serait possible d'inclure des options (dossier `songbook/includes/`, sauf pour `patacrep` & `layout`):

`layout` (reste tel-quel, considère les options `latex`)
* `chordedoptions` inclus si le `booktype` est `chorded` (`show=True`)
* `index` inclus pour gérer authors & titles

`patacrep` hérite de layout et inclus les templates suivants:
* `color` inclus pour gérer les couleurs
* `titlepage` inclus pour gérer la page de titre

Avec les templates de jinja, l'inclusion va conserver les même priorités ? (et donc les possibilités de remplacement)

Du coup `styles` pourrait aussi être déplacé dans `templates`

**Comment by paternal** [comment]
> Plutôt que d'hériter en chaînes, est-ce qu'il serait possible d'inclure des options (dossier songbook/includes/, sauf pour patacrep & layout):

Je ne comprends pas ce que `songbook/includes` vient faire là-dedans (ou alors, je n'ai pas compris la suite).


Pour les templates en général, j'aimais bien l'idée de séparer ce qui est nécessaire (default, qui inclus un index, les chansons, soit des choses techniques) du superflu (patacrep, qui inclut une page de titres, des couleurs, des polices... tout ça est une question de goût). L'idée étant, que si je veux améliorer un carnet de chant, en étendant un template de patacrep : 
- si les améliorations de patacrep me plaisent, j'utilise `patacrep` ;
- si elles ne me plaisent pas et que je veux repartir d'une version « neutre », j'utilise `default`.

**Comment by oliverpool** [comment]
> Je ne comprends pas ce que `songbook/includes` vient faire là-dedans (ou alors, je n'ai pas compris la suite).

Plutôt que de faire que de l'héritage, il doit être possible de faire des [`include`](http://jinja.pocoo.org/docs/dev/templates/#include) (ou `import` en LaTeX) pour inclure juste une fonctionnalité (template partiel: index des auteurs, index des titres, un thème coloré, une page d'accords; rangé dans `songbook/includes` ou `songbook/partials`).

> - si les améliorations de patacrep me plaisent, j'utilise `patacrep` ;
- si elles ne me plaisent pas et que je veux repartir d'une version « neutre », j'utilise `default`.

Cela me convient parfaitement, mais j'ai toujours du mal à savoir quel template je devrais utiliser.

Avec ce système d'include, il doit être possible de ne faire plus que 2 (ou 3) templates: `layout` qui devient la base absolument nécessaire pour faire un carnet (sans aucune fioriture) et `patacrep` qui hérite de `layout` et qui fait des `includes` de tous les templates partiels.

Si je fait mon propre template, il suffit de copier/coller `patacrep` et de virer les `includes` que je ne souhaite pas.
