### ISSUE TITLE
Voir si la propriété `config` de `Song` peut-être supprimé

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#170]
*Suite de #102*

Actuellement on stocke l'argument [`config`](https://github.com/patacrep/patacrep/blob/9db2a86c72d7e5c4307c168b8a26ca94eee14838/patacrep/songs/__init__.py#L111) tel quel.

Je trouve cet argument (et son utilisation) assez opaque, car certaines clés doivent être définies et d'autres non...
Je pense que c'est bien si on arrive à le séparer en plusieurs arguments (`encoding`, `words`, `default_lang`, `use_cache`, `datadirs`...)
Il n'est pas non plus idéal d'avoir trop d'arguments.

**Comment by paternal** [comment]
C'était bien ce que j'avais en tête avec #102. J'attends d'avoir résolu #111 avant de me lancer là dedans.

**Comment by paternal** [comment]
Vu la variété de valeurs de `config` utilisés, j'ai l'impression que garder l'argument `config`, c'est bien. Je propose donc de fermer cette issue sans rien faire.

**Comment by oliverpool** [comment]
Ca me va
