### ISSUE TITLE
Faire un binaire patatools

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#171]
Voir les commentaires de 96b2c3201ad021d57f2988a3b714d420d02f11d0

> * `patatools cache clean` : vide le cache ;
* `patatools song convert` : conversion de chanson (qui a été ajouté récemment) ;
* et plus au fil des besoins…

Il faut que je copie-colle du code d'un autre projet, pour la gestion automatique des sous-commandes.

**Comment by oliverpool** [comment]
https://github.com/patacrep/pataextra est coordonner avec patatools je pense.

**Comment by paternal** [comment]
> https://github.com/patacrep/pataextra est à coordonner avec patatools je pense.

- `patatools` contient des binaires
- `pataextra` contient quelques binaires (qui sont à mon avis plutôt obsolètes), mais surtout des outils (comme la coloration syntaxique) qui n'ont pas leur place dans patatools.

**Comment by paternal** [comment]
Proposition de fermeture dans #189.

**Comment by paternal** [comment]
C'est la troisième fois que j'écris [ces lignes de code](https://github.com/patacrep/patacrep/blob/patatools/patacrep/tools/__main__.py#L19-L113) dans un projet : un jour, j'en ferai peut-être un module indépendant…
