### ISSUE TITLE
Récupérer les options de templates de manière plus propre

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#186]
Actuellement, les options de templates sont récupérées [avec une grosse regexp](https://github.com/patacrep/patacrep/blob/c1a871b5499cb1a1250a0ab5c27f5043152533ce/patacrep/templates.py#L24-L43). C'est fragile.

En [interprétant le template comme un module](http://jinja.pocoo.org/docs/dev/api/#jinja2.Template.module), et en améliorant [`VariablesExtension`](https://github.com/patacrep/patacrep/blob/c1a871b5499cb1a1250a0ab5c27f5043152533ce/patacrep/templates.py#L46-L59) (en s'inspirant de [l'extension `do`](http://jinja.pocoo.org/docs/dev/extensions/#expression-statement)), on peut utiliser l'interpréteur jinja2 plutôt qu'une regexp fragile pour récupérer ces valeurs.

**Comment by paternal** [comment]
Pas sûr qu'il y ait vraiment quelque chose à faire ici… Un des problèmes est celui de l'œuf et de la poule : il faut analyser le template pour récupérer les variables, mais il faut les variables pour exécuter le template.


On peut quand même analyser le template sans l'exécuter:

~~~python
from jinja2 import Environment

template = Environment().from_string("""
FOO {{bar}}
{% macro template_options() %}
tagada
tsoin tsoin
{% endmacro %}
FOO {{bar}}
""")
print(template.module.template_options())
~~~

Mais le problème est que je pense qu'une macré *écraserait* celle des templates parents, et les options de ces derniers seraient perdues.


Mais idées avec les extensions ne fonctionneraient pourtant pas, pour le problème de l'œuf et la poule cités plus haut.

J'ai l'impression qu'on ne pourra pas faire mieux que la version actuelle…

**Comment by oliverpool** [comment]
Mergé dans `yaml_content`
