### ISSUE TITLE
cwd, songdir & datadir

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#204]
Je trouve la situation au niveau des `songdir`, des `datadir` et de `cwd` assez confuse.

*En me basant sur la branche `yaml_ext` (PR #203)*

Les datadirs sont composés des dossiers spécifiés dans le fichier.yaml, ainsi que le dossier où réside le fichier.yaml.

Les songdirs sont les sous-dossiers `songs` des répertoires précédents.

`cwd` ajoute en tête des songdir, le sous-dossier relatif au répertoire du fichier.yaml (le comportement en cas de `cwd` imbriqués est d'ailleurs visiblement erroné).

---

A cet effet, je propose :
- de continuer à rajouter de manière automatique le dossier du fichier.yaml à la liste des datadir (comme ça on peut dire qu'un dossier typique de carnet comporte un fichier.yaml et un dossier `songs`)
- d'arrêter d'ajouter le traitement particulier de `cwd` (et de bien préciser dans la doc, que `cwd` est relatif aux dossiers `songs`)

**Comment by paternal** [comment]
J'ai toujours trouvé aussi que le traitement de `cwd` était un peu bizarre.

> de continuer à rajouter de manière automatique le dossier du fichier.yaml à la liste des datadir (comme ça on peut dire qu'un dossier typique de carnet comporte un fichier.yaml et un dossier songs)

Ok.

> d'arrêter d'ajouter le traitement particulier de cwd (et de bien préciser dans la doc, que cwd est relatif aux dossiers songs)

Est-ce que renommer `cwd` en `csd` (`change song directory`) serait alors pertinent ?

**Comment by oliverpool** [comment]
> Est-ce que renommer `cwd` en `csd` (`change song directory`) serait alors pertinent ?

Je proposerai même `cd`: pour les utilisateurs de la ligne de commande, ça devient très compréhensible (la seule subtilité étant le répertoire de départ).

**Comment by paternal** [comment]
Une question que je me pose tout de même :

1. Est-ce qu'un dossier `.yaml` (avec un `include`) peut-être placé hors d'un dossier `songs` ?
2. Si oui, est-ce que donnera un `include foo.yaml` après un `cd`, si `cd` ne concerne que le dossier `songs` ?

**Comment by oliverpool** [comment]
> 1. Est-ce qu'un dossier `.yaml` (avec un `include`) peut-être placé hors d'un dossier `songs` ?

Actuellement non: https://github.com/patacrep/patacrep/blob/master/patacrep/content/include.py#L22

On parcours à la main les dossiers `songs` des datadir (en ignorant le `cwd` éventuel).

---

Je pense que le problème est plug général : comment peut-on gérer de manière cohérente l'inclusion des fichier `.tsg`, `.csg`, `include`, `.tex` ?

Actuellement:
* `tsg`, `csg`: cherchés dans les dossiers `songdir` (avec `cd` éventuel)
* `include`: cherché dans les dossiers `datadir(s)/songs/`
* `tex`: cherché dans les dossiers `songdir` (avec `cd` éventuel), puis `datadir(s)`, puis `datadir(s)/latex`

Bref, c'est un peu le bazar...

Je pense que le `cd` est surtout là pour servir de raccourcis (pour éviter de réécrire le chemin pour chaque chanson) et qu'il ne devrait affecter que les `songdir`.
Les `include` et les `tex` sont normalement plus rares: je propose que les `includes` soient cherchés à partir des `datadir(s)` (indépendamment de `cd`) et que les `tex` soient cherchés à partir de `datadir(s)/latex` uniquement.

**Comment by oliverpool** [comment]
Et en fait, c'est un peu lié à #164

**Comment by paternal** [comment]
> Je pense que le cd est surtout là pour servir de raccourcis (pour éviter de réécrire le chemin pour chaque chanson) et qu'il ne devrait affecter que les songdir.
> Les include et les tex sont normalement plus rares: je propose que les includes soient cherchés à partir des datadir(s) (indépendamment de cd) et que les tex soient cherchés à partir de datadir(s)/latex uniquement.

Ok.
