### ISSUE TITLE
what are prerequisites for running paracrep?

### ISSUE THREAD

**Issue by kether667** [patacrep/patacrep#229]
i'm using ubuntu 16.04
i've installed paracrep via `pip3 install patacrep` and i'm trying to build examples but it errors out saying that `lualatex` is missing. I cannot figure out what package should be installed, i tried `sudo apt-get install texlive-luatex`, but it's luatex not lualatex, anyways i've created symbolic link and now it errors out saying `lilypond` is missing... 

Could you please be add prerequisites to readme?

**Comment by kether667** [comment]
finally i got it to work,

that is needed for ubuntu:

`sudo apt-get install texlive texlive-latex-base texlive-latex-recommended texlive-latex-extra`
`sudo apt-get install texlive-lang-english sudo apt-get install texlive-lang-french`
`sudo apt-get install texlive-xetex`

`sudo ln -s /usr/bin/luatex /usr/bin/lualatex`

**Comment by oliverpool** [comment]
The documentation is currently only in french: https://patacrep.readthedocs.io/fr/latest/installation.html#debian

But i find the `sudo ln -s /usr/bin/luatex /usr/bin/lualatex` strange... For me it is already included in the texlive package !

Anyway, if everything is now running fine, can we close this issue?

**Comment by kether667** [comment]
sure, although i would add that link to readme.md as it's not obvious when someone comes across this repo and tries to use it

**Comment by oliverpool** [comment]
Like this: https://github.com/patacrep/patacrep/blob/45bd4046038db4e63777b2fa5e16a2ff4fe2b9df/README.rst ?

**Comment by kether667** [comment]
thanks you i'm sure that will be helpful to others

**Comment by oliverpool** [comment]
Thank you for your comments!
