### ISSUE TITLE
Pages blanches aléatoires

### ISSUE THREAD

**Issue by cypriani** [patacrep/patacrep#245]
Avec songbook 5.1.1, le PDF produit contient des pages blanches, de manière apparemment aléatoire, tout au long du document. Il ne manque aucune chanson, les pages sont ajoutées. À noter que deux compilations successives du même recueil produisent le même résultat, donc ce n'est peut-être pas si aléatoire que ça.
Par exemple, sur le recueil Naheulbeuk, le PDF fait 34 pages, dont deux pages blanches (pages 12 et 20) : [naheulbeuk.pdf](https://github.com/patacrep/patacrep/files/419418/naheulbeuk.pdf)

Je ne vois pas trop par où attaquer l'enquête. Quelqu'un a observé le même problème ?

**Comment by oliverpool** [comment]
Effectivement, c'est bizarre.
C'est habituellement justifié par le fait pour que les deux pages d'une chanson soit en vis-à-vis (pour éviter de tourner la page), mais dans ton exemple, je ne vois rien de tel.

Au contraire, les chansons n°22 et n°27 demandent de tourner la page (alors qu'elles pourraient passer sur deux pages côte-à-côte).

Est-ce que tu pourrais partager le fichier `.tex` ? (avec l'option `-s=tex,pdf,sbx,pdf` pour [éviter le `clean` final](https://github.com/patacrep/patacrep/blob/master/patacrep/build.py#L19))

**Comment by cypriani** [comment]
[naheulbeuk.tex.gz](https://github.com/patacrep/patacrep/files/425352/naheulbeuk.tex.gz)

(À noter que j'ai désactivé lilypond dans naheulbeuk.yaml.)

**Comment by cypriani** [comment]
Problème toujours présent avec songbook 5.1.2 et TexLive 20161008. Sur une autre machine, mais système similaire (Debian unstable amd64).

**Comment by crep4ever** [comment]
J'ai le même problème (ubuntu 16.10, texlive 2016).
Après tout un tas d'essais, ça vient d'un comportement différent du package songs entre lualatex (pages blanches, colonnes flushées en bas) et pdflatex (tout ok).

À noter que xelatex semble ok également.

**Comment by crep4ever** [comment]
Si pas besoin de lilypond, un workaround consiste à changer `compiler = "lualatex"` par `compiler = "xelatex"` dans `build.py` et de commenter la section `\iflilypondauto` dans `data/templates/styles/patacrep.sty`

**Comment by cypriani** [comment]
Ah, c'est bon à savoir, j'essayerai ça en attendant mieux. C'est vrai que j'avais remarqué aussi le fait que les colonnes sont alignées en bas, ce que je trouve assez perturbant d'ailleurs.

**Comment by cypriani** [comment]
Je ferme, le souci est résolu depuis quelque temps déjà.
