### ISSUE TITLE
Incompatibilité entre diagramreminder et ukulele

### ISSUE THREAD

**Issue by sbaro** [patacrep/patacrep#251]
Bonjour,
Il semble y avoir une incompatibilité entre diagramreminder = all et instrument = ukulele. Quand on utilise ces deux options, les diagrammes d'accords n'apparaissent pas sur les pages de chanson. Testé avec patadata et example-crepbook.yaml, sur la version 5.1.2 de patacrep.

Merci d'avance.

**Comment by oliverpool** [comment]
J'ai enfin trouvé le temps de faire des tests. D'après ce que je vois, c'est juste parce qu'il n'y a aucun accord de Ukulele défini dans les chants de `example-crepbook.yaml`.

Par exemple dans [Chevaliers de la table ronde](https://github.com/patacrep/patacrep/blob/e1e024d2ce9f102909e03b26125dc51eedbc03d1/examples/songs/chevaliers_de_la_table_ronde.tsg#L7-L9), seuls des `gtab` sont définis (et aucun `utab`)

**Comment by Spheerys** [comment]
Je ne saisi pas bien : la génération des accords ne se fait pas automatiquement, en fonction de leur nom, quelque soit le format de sortie (guitare ou ukulélé) ?

**Comment by oliverpool** [comment]
Non (du moins, pas encore: #128), il faut que ceux-ci soient renseignés au début du chant

**Comment by oliverpool** [comment]
Documentation pour les chants au format LaTeX: https://patacrep.readthedocs.io/fr/latest/song/latex.html#diagrammes-des-accords

**Comment by Spheerys** [comment]
OK je saisi mieux comment ça marche.
Ca serait vraiment génial que la génération des accords guitare/ukulélé puissent être automatisés en effet... Car là pour le coup, je ne saisissais pas pourquoi ils n'étaient pas générés malgré la bonne option dans le .yaml
