### ISSUE TITLE
Nouveaux mainteneurs

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patacrep#257]
I'm writing this in french, as I believe all concerned people speak it. If you don't, please tell me and I'll translate it !

----

Salut !

Après un peu de travail sur patacrep il y a quelques années, je n'ai plus du tout le temps de m'en occuper aujourd'hui. Il me semble que c'est aussi vrai pour @oliverpool, qui fait parti des derniers à trainer dans le coin et à écrire un peu de code/merger des PR. 

Il me parait dommage d'abandonner complètement le logiciel, surtout quand il est encore utilisé (il y a 6 PR sur patadata, par 4 personnes différentes). 

Je propose donc de donner les droits en écriture à d'autres, qui pourrait ainsi continuer à faire vivre patacrep ! Je pense en particulier à tout ceux qui ont proposé des PR dans les derniers mois : @Grahack, @jaryn, @OresteVisari, @julienpaitel, @Spheerys.

L'idée n'est pas de modifier fortement le code ou d'obliger des personnes à travailler, mais simplement d'être sur qu'il y ai des gens qui reste dans le coin pour faire vivre le projet et merger les PR!

Dites moi ce que vous en pensez, et n'hésitez pas à mentionner d'autres personnes qui pourrait être intéressés.

**Comment by Spheerys** [comment]
pas super dispo en ce moment mais si je peux filer un coup de main en validant des PR, ça ne me pose pas de pb :)

**Comment by Grahack** [comment]
Partant.

**Comment by Luthaf** [comment]
@Spheerys et @Grahack, je vous ai invité dans l'organisation patacrep ! Merci à vous =)

**Comment by Grahack** [comment]
Merci pour votre confiance. Qu’en est-il du site? du forum?

**Comment by OresteVisari** [comment]
Partant aussi pour filer un coup de main sur certaines PR !

**Comment by Grahack** [comment]
Y a aussi les releases et tout!
Tiens, qques questions au passage:
* y a-t-il de la doc pour les néo devs-mainteneurs?
* par exemple je vais merger le nouveau `songs.sty` pour pouvoir avoir les barrés, y a-t-il des précautions à prendre avant de mettre dans `patadata` du code incompatible avec le vieux `songs.sty`?

**Comment by Luthaf** [comment]
@OresteVisari, je t'ai invité aussi !

Pour le site et le forum, il faut que je regarde, je dois avoir les droits pour ajouter des admins.

Pour les releases, @oliverpool avait mis en place une publication automatique des release github sur Pypi. En gros Travis publie automatiquement la release avec mon token (qui est directement encrypté sur Travis). Mais je peut ajouter quelqu'un d'autre sur pypi sans problème.

Pour la doc, il n'y a rien de particulier ... Il n'existe que le manuel utilisateur. Le code est Python + LaTeX, donc connaitre un peu des deux aide.

> par exemple je vais merger le nouveau songs.sty pour pouvoir avoir les barrés, y a-t-il des précautions à prendre avant de mettre dans patadata du code incompatible avec le vieux songs.sty?

Dans ce cas particulier, ça pourrait valoir le coup de faire une nouvelle release de patacrep avant de modifier patadata.

**Comment by oliverpool** [comment]
@Luthaf excellente initiative ! (J'ai en effet d'autres priorités actuellement que de maintenir patacrep)

> Merci pour votre confiance. Qu’en est-il du site? du forum?

A ma connaissance, tout cela est géré par @lohrun 

> y a-t-il de la doc pour les néo devs-mainteneurs?

pas vraiment... Mais ça peut-être l'occasion d'en créer une !
Tu peux ouvrir une nouvelle issue sous forme de question (par exemple, _"comment ajouter une nouvelle configuration au fichier .yaml ?"_ ou _"comment rajouter des nouveaux mot-clés au format ChordPro ?"_, selon ce que tu veux faire) et j'essayerai d'être réactif pour apporter des réponses ! (je n'aurai pas le courage de commencer une doc à partir de zéro, mais si tu as une question précise, je pourrais plus facilement y répondre)

> par exemple je vais merger le nouveau songs.sty pour pouvoir avoir les barrés, y a-t-il des précautions à prendre avant de mettre dans patadata du code incompatible avec le vieux songs.sty?

Le nouveau `songs.sty` devrait compatible non ? Un test simple serait de simplement compiler patadata avec le nouveau `songs.sty` : si ça compile bien, c'est déjà pas mal (cela n'empêche pas de provoquer éventuellement des bugs d'affichages)

**Comment by Grahack** [comment]
> Le nouveau `songs.sty` devrait compatible non ? Un test simple serait de simplement compiler patadata avec le nouveau `songs.sty` [...]

Oui, ça compile et je n'ai pas vu de bug d'affichage.

Le soucis est plutôt le suivant: on va faire des modifs sur `patadata` qui nécessitent le nouveau `songs.sty` (barrés). On va avoir des utilisateurs qui vont mettre leur `patadata` à jour mais qui vont compiler avec le vieux `patacrep`. Faudrait minimiser le nombre de ces personnes.

**Comment by lazouz** [comment]
Hello ! 

Je ne suis pas encore contributeur, mais ça ne saurait tarder, je pense que patacrep est un projet important à pérenniser.

J'ai cru voir des références scoutes de ci de là... c'est aussi pour ça que je suis là :p

**Comment by takuyozora** [comment]
Salut !

Avec un ami on serait pas mal intéressés pour comprendre un peu mieux comment fonctionne patacrep et pour éventuellement le faire évoluer. 
Par contre j'ai beau avoir quelques bonnes connaissances en LaTeX et en Python j'ai passé la soirée à fouiller dans le code et quand on débarque, ce n'est pas très simple de s'y retrouver. Le projet est conséquent ce qui explique en partie la courbe d'apprentissage, mais à mon avis il manque également un peu de documentation.

Sans parler d'une doc exhaustive, serait-il envisageable d'avoir un petit topo de l'architecture du projet, du workflow interne, et du fonctionnement des différents bouts de LaTeX ?

En tout cas le projet me fait de l'œil depuis quelques années, et j'ai enfin un petit peu de temps à lui consacrer, du coup je suis motivé pour creuser. 
J'aimerais notamment comprendre ce qui provoque le fait que, en mode multi-colonne et multi-chant-par-page, parfois deux chants vont s'enchaîner correctement et parfois un chant va passer à la page suivante alors qu'il lui reste au moins une demie colonne voir même une colonne entière.

Exemple : 

![image](https://user-images.githubusercontent.com/304811/48591695-45ed6080-e945-11e8-9418-0a153a2d561f.png)

**Comment by paternal** [comment]
> J'aimerais notamment comprendre ce qui provoque le fait que, en mode multi-colonne et multi-chant-par-page, parfois deux chants vont s'enchaîner correctement et parfois un chant va passer à la page suivante alors qu'il lui reste au moins une demie colonne voir même une colonne entière.

Ça, c'est géré par le paquet [songs](http://songs.sourceforge.net/) (utilisé pour produire les chants). Vu ton exemple, je suppose que songs essaye, autant que possible, de garder un chant sur une seule page : dans le premier exemple, « Cupidon s'en fout » tient sur une page, donc on le met là, dans le second « L'Orage » ne tient pas dans la page, donc on passe à la page suivante.

**Comment by oliverpool** [comment]
@takuyozora j'ai essayé d'ébaucher un aperçu de ce qui ce passe : https://github.com/patacrep/patacrep/pull/261
N'hésite pas à y commenter si ça te convient ou si il te manque des éléments.

**Comment by takuyozora** [comment]
Merci pour vos réponses et votre réactivité !

En ce qui concerne ma question sur le placement des pages j'ai ouvert une issue dédiée pour ne pas polluer celle-ci : https://github.com/patacrep/patacrep/issues/262

De même pour la PR : https://github.com/patacrep/patacrep/pull/261

**Comment by takuyozora** [comment]
Bonjour,

Après quelques années à me servir de patacrep dans mon coin pour faire des carnets, j'ai fini par rentrer un peu plus profondément dans le code et faire quelques changements autant côté Python que LaTeX. Maintenant j'essaye de tout restructurer pour pouvoir fonctionner le plus possible avec la version mainstream de patacrep et avoir mes changements uniquement dans des datadir, mais ça devient de plus en plus compliqué et au final je pense que certains ajouts pourraient profiter à plus de monde.

Du coup je serais intéressé par rejoindre l'équipe de développement, pour discuter de la suite du projet et pouvoir participer à celle-ci.

**Comment by Grahack** [comment]
Salut, j’ai été catapulté mainteneur lors du [Grand Chambardement](https://github.com/patacrep/patacrep/issues/257). Je m’y connais bien en Python mais pas très bien dans le système `patacrep` et autres. Je suis plutôt dans les vérifs de la musique, mais j’aimerais bien contribuer au code aussi.

Tu es le bienvenu. Fais péter des beaux commits bien expliqués dans des PR et c’est parti!!! Je ne suis pas contre non plus te promouvoir, faut voir avec les autres.

**Comment by oliverpool** [comment]
Salut @takuyozora

Tu est le bienvenu pour faire des "merge-requests" avec tes changements (même sans être membre de l'équipe de dev) et participer aux différentes discussions !
Je préfère attendre 1 ou 2 MR avant de te promouvoir (pour être sûr que tout le monde soit bien intentionné).

Je ne suis malheureusement plus très actif sur ce projet (ça fait longtemps que je n'ai pas eut besoin de faire un carnet de chants...), mais j'essayerai de prendre le temps de faire une revue de tes MR techniques (pour la musique @Grahack sera mieux placé).

N'hésite pas à me "pinger" (@oliverpool) si tu as des questions :-)

**Comment by takuyozora** [comment]
> Tu est le bienvenu pour faire des "merge-requests" avec tes changements (même sans être membre de l'équipe de dev) et participer aux différentes discussions !
> Je préfère attendre 1 ou 2 MR avant de te promouvoir (pour être sûr que tout le monde soit bien intentionné).

D'acc o d'acc ! Il y aura sûrement à redire, mais je vais essayer de faire ça bien, j'espère dans les semaines qui viennent en fonction du taff qu'il va me rester à côté.

**Comment by oliverpool** [comment]
Voir #277
