### ISSUE TITLE
`l3backend-pdfmode.def' not found

### ISSUE THREAD

**Issue by danielbenoilid** [patacrep/patacrep#263]
Hello,

Quand je compile mon premier songbook, je ne parviens pas à générer le pdf (erreur `l3backend-pdfmode.def' not found).
Sauriez-vous comment fixer ce problème ?

Merci beaucoup pour votre aide.
[prems.log](https://github.com/patacrep/patacrep/files/3367903/prems.log)

**Comment by Grahack** [comment]
Bonne question.

Marrant, elle est apparue ici il y a qques heures:
https://tex.stackexchange.com/questions/499082/file-l3backend-pdfmode-def-not-found-when-loading-expl3

Chez moi:

    $ locate expl3
    /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex
    /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-generic.tex
    /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.lua
    /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty

As-tu ce paquet aussi?

Mais `locate l3backend` ne retourne rien, donc sans doute pas besoin.

Je re-triple-checkerais la procédure d’install de Patacrep. D’ailleurs, as-tu utilisé un paquet tout fait ou tu as installé à partir des sources?

**Comment by danielbenoilid** [comment]
Merci beaucoup pour ton retour.
J’ai effectivement les même fichier (dans ce dossier : C:\Users\Daniel\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel)
J’ai installé patacrep directement depuis python (pip patacrep).

Je t’avoue que suis complètement bloqué à ce stade. Saurais-tu si un des contributeur du projet serait intéressé par m’aider (à mon bureau à Paris ou en remote). J’ai un budget de 250€ pour produire le carnet de chants.

1000 mercis


_________________________________________________________________________

Daniel Benoilid
Directeur
\\/irk<https://www.wirk.io/>
Tel.  +33 1 85 09 62 60
Mobile  +33 6 18 05 33 54
_________________________________________________________________________________________________

De : Prof Gra <notifications@github.com>
Envoyé : lundi 8 juillet 2019 13:46
À : patacrep/patacrep <patacrep@noreply.github.com>
Cc : Daniel Benoilid <daniel@wirk.io>; Author <author@noreply.github.com>
Objet : Re: [patacrep/patacrep] `l3backend-pdfmode.def' not found (#263)


Bonne question.

Marrant, elle est apparue ici il y a qques heures:
https://tex.stackexchange.com/questions/499082/file-l3backend-pdfmode-def-not-found-when-loading-expl3

Chez moi:

$ locate expl3



/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex



/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-generic.tex



/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.lua



/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty



As-tu ce paquet aussi?

Mais locate l3backend ne retourne rien, donc sans doute pas besoin.

Je re-triple-checkerais la procédure d’install de Patacrep. D’ailleurs, as-tu utilisé un paquet tout fait ou tu as installé à partir des sources?

**Comment by Grahack** [comment]
Je n’ai pour l’instant pas d’autre idée que la réinstallation de MikTeX. Peut-être déjà tentée?
Sinon j’essaie de te contacter demain.

**Comment by Grahack** [comment]
Alors?

**Comment by danielbenoilid** [comment]
Ca y est, j’ai réussi à compiler ce matin.
Le proclème venait de Miktex (mis à jour et ajouté le package l3backend).

1000 mercis pour ton aide.

_________________________________________________________________________________________________

Daniel Benoilid
Directeur
\\/irk<https://www.wirk.io/>
Tel.  +33 1 85 09 62 60
Mobile  +33 6 18 05 33 54
_________________________________________________________________________________________________

De : Prof Gra <notifications@github.com>
Envoyé : mardi 9 juillet 2019 19:30
À : patacrep/patacrep <patacrep@noreply.github.com>
Cc : Daniel Benoilid <daniel@wirk.io>; Author <author@noreply.github.com>
Objet : Re: [patacrep/patacrep] `l3backend-pdfmode.def' not found (#263)


Alors?
