### ISSUE TITLE
www.patacrep.com is now patacrep.fr

### ISSUE THREAD

**Issue by luboss** [patacrep/patacrep#271]
The page www.patacrep.com was working some time ago (I was there about 2-3 months ago) but isn’t anymore. Looks like a DNS issue.
Btw I love this project, keep it on!

---
**_Contributor edit_: site is back up under https://patacrep.fr/**

**Comment by oliverpool** [comment]
@crep4ever was the owner of this domain I think.

This domain expired on 2021-06-04T10:33 and it seems to have been bought by some reseller/advertiser, so probably hard to get back.
Maybe it would be possible to host the content under another domain

**Comment by luboss** [comment]
Understood. That's about the domain, what about its web server hosting itself, is the site still running somewhere? If so, what its IP please?

**Comment by oliverpool** [comment]
The content seems to be accessible at https://github.com/crep4ever/patacrep (no idea how current it is)

**Comment by luboss** [comment]
Well, it doesn't host documentation ([doc_en.pdf](http://www.patacrep.com/data/documents/doc_en.pdf)) and windows binaries

**Comment by luboss** [comment]
I could find some archived versions on WayBackMachine:
[www.patacrep.com](https://web.archive.org/web/20210210220924/http://www.patacrep.com/en/index.php) (Feb 2021)
[doc_en.pdf](https://web.archive.org/web/20160606000605/www.patacrep.com/data/documents/doc_en.pdf) (2016)
[Songbook-Client-0.7.7-Setup.exe](https://web.archive.org/web/20160605012054/http://patacrep.com/data/songbook-client/windows/Songbook-Client-0.7.7-Setup.exe)

**Comment by atsju** [comment]
Formated : [patacrep.fr](https://patacrep.fr/) is up
It took me a long time to find the website, consider editing issue title adding the link with proper formatting.

**Comment by oliverpool** [comment]
@atsju thanks for the hint. I edited the original post and the title. I also adjusted the homepage of the git repo.

Feel free to make a PR if you find any old reference in code!

**Comment by atsju** [comment]
@oliverpool  done in #275

**Comment by oliverpool** [comment]
Thanks. I'm currently on holidays, but will try to check these in May at the latest (if not, feel free to ping me again by then :see_no_evil: )
