### ISSUE TITLE
Problème dans le pdf généré avec tablatures

### ISSUE THREAD

**Issue by Flore-mozfr** [patacrep/patacrep#276]
Bonjour à tous,

Je viens d'installer patacrep et après avoir résolu les soucis de Jinja et de yaml, je peux enfin générer des pdf.
Mais j'ai un gros souci : dès qu'il y a des tablatures (ou simplement si je ne mets pas chords: show: no  dans le yaml), toutes les lignes avec accords sont en vrac : pas de retour à la ligne, décalage, empiètement sur la ligne de refrain...
Si je n'affiche plus les accords, c'est parfait.
Et ceci même avec les fichiers qui viennent directement de patacrep et qui devraient fonctionner correctement
![Capture d’écran 2022-09-02 011417](https://user-images.githubusercontent.com/6987429/188027956-f3fb9f2d-d593-46eb-89ac-3f1b959a0d16.png)
Je suis sous windows 10 avec patacrep, release, mikTex (dernière version).

C'est un peu une bouteille à la mer que je lance, mais si quelqu'un a une idée de pourquoi ça ne marche pas, ça serait vraiment sympa.

**Comment by sgelis** [comment]
Même problème ici :cry:. Le problème est relativement récent chez moi : j'ai écrit une tab il y a 3 mois, tout s'est bien passé. Mais aujourd'hui, patatras !

Des mainteneurs toujours dispo pour donner une piste ?

**Comment by Flore-mozfr** [comment]
J'ai trouvé une solution de contournement : mettre des retours à la ligne à chaque fin de ligne avec des accords (ce qui est expressément déconseillé dans la doc, mais bon). Et du coup, ça marche. Par contre, ça veut dire reprendre tous les fichiers.

Entretemps, je suis repassée sous Mac (j'étais temporairement sous windows) et là aucun souci avec les fichiers nouveaux ou anciens. Je soupçonne que le problème vient de windows et pas de patacrep, peut-être Miktex qui fait n'imp'.

**Comment by sgelis** [comment]
Pour ma part, étant donné que le projet est mort (et c'est bien dommage), j'ai fait une image Docker qui empaquette tout le nécessaire pour faire tourner Patacrep et LilyPond avec leurs vieilles dépendances.

L'image est ici : https://hub.docker.com/r/sgelis/patacrep, ainsi que les instructions pour l'utiliser.

**Comment by sgelis** [comment]
Bonne nouvelle : j'ai eu une grosse mise à jour de LaTeX sur ma machine ce matin (GNU/Linux Debian testing/unstable) et ça a l'air de fonctionner à nouveau :partying_face:

Quelqu'un peut confirmer ?

**Comment by xouillet** [comment]
J'ai toujours le soucis sur archilinux (texlive 2023.66594-5)

**Comment by Victor-Morel** [comment]
Idem de mon côté (arch texlive 2023.66594-19)

**Comment by cypriani** [comment]
Le problème existe toujours avec patacrep 5.2.0 sous Debian sid. Est-ce que quelqu'un avait pu identifier sa cause ?

**Comment by Flore-mozfr** [comment]
Bonsoir à tous,

J'ai réinstallé patacrep et me suis retrouvée de nouveau confrontée à ce problème. J'ai cherché un peu partout sur internet et trouvé la raison : une mise à jour de Latex qui a changé un comportement
https://tex.stackexchange.com/questions/650106/recent-update-broke-songs-package

Latex a fourni un first aid package pour corriger ça. Et finalement, la bonne nouvelle, c'est que c'est ultra simple à patcher pour patacrep.
Editer le fichier songs.sty dans "patacrep/data/templates/styles/"

Remplacer le paragraphe : 
`\newcommand\SB@obeylines{%
  \let\par\SB@par%
  \obeylines%
  \let\@par\SB@@par%
}`
par 
`\newcommand\SB@obeylines{%
  \let\obeyedline\SB@par%
  \obeylines%
  \let\@par\SB@@par%
}`

Et tout rentre dans l'ordre

Bons carnets de chants à tous

**Comment by oliverpool** [comment]
Merci pour l'enquête approfondie et la proposition de résolution!

J'ai fait le merge du fix tel quel (sans tester, car je n'utilise plus patacrep moi-même), du coup je suppose que cette issue peut-être fermée?

**Comment by Flore-mozfr** [comment]
J'ai testé chez moi et ça marche (fedora 40).
Si @cypriani peut confirmer que ça marche pour lui aussi sous Debian, ce serait parfait.

**Comment by sgelis** [comment]
Je viens de tester, c'est tout bon sur Debian aussi, merci beaucoup @Flore-mozfr :partying_face:. Je fais une release PyPI de ce pas !

**Comment by sgelis** [comment]
Et voilà : https://pypi.org/project/patacrep/5.2.1/.

Merci encore @Flore-mozfr :pray:

**Comment by cypriani** [comment]
Je confirme, merci beaucoup pour le correctif @Flore-mozfr, et pour le paquet @sgelis !

**Comment by Jacko-757** [comment]
Bonjour je n'arrive pas à installer Patacrep je suis sous debian 12.14.0 est-ce que ce logiciel est toujours maintenu ?

**Comment by Jacko-757** [comment]
j'ai installé Songbook-Client-0.7.7 sous windows il s'est bien installé il se lance mais je ne peut pas exporter une chanson en pdf j'ai une erreur en rouge

! I can't find file `default.tex'.

le fichier log entier

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>Rem manually performs "make clean"

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>FOR %A IN (*.aux *.d *.toc *.out *.log *.nav *.snm *.sbx *.sxd) DO DEL %A

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>DEL texput.log

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>Rem remove temporary covers

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>FOR %A IN (cache\songbook*.jpg) DO DEL %A

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>Rem build tex file from songbook file

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>python songbook.py --songbook=books[default.sb](http://default.sb/) --output=default.tex

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>Rem 1st pdf compilation

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013>pdflatex default.tex

C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013\songbook.py:198: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\g"? A raw string is also an option.

idx = map(lambda x: x.replace("\getname", name), matchRegexp(indexPattern, tmpl))

File "C:\Program Files (x86)\Songbook-Client\songbook-10-04-2013\songbook.py", line 210

print "No usage information yet."

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

This is pdfTeX, Version 3.141592653-2.6-1.40.28 (MiKTeX 25.12) (preloaded format=pdflatex.fmt)

restricted \write18 enabled.

entering extended mode

! I can't find file `default.tex'.

<*> default.tex

(Press Enter to retry, or Control-C to exit)

Please type another input file name:

**Comment by Jacko-757** [comment]
Mais j'aimerai mieux l'installer sous mon debian

**Comment by Jacko-757** [comment]
j'ai essayé de l'installer en suivant les explication du site https://pypi.org/project/patacrep/ avec la version patacrep 5.2.1

Using pip

For the stable version, as simple as:

pip3 install patacrep

And upgrade to the latest release:

pip3 install patacrep -U

Or for the latest version:

pip3 install https://github.com/patacrep/patacrep/archive/master.zip

ça ne fonctionne pas

je n'arrive pas non plus a cloner le depot github


For developement

Clone Patacrep repos:

git clone git://github.com/patacrep/patacrep.git
cd patacrep
pip3 install -r Requirements.txt
python3 setup.py develop

donc je seche si quelqu'un aurait une solution je suis preneur
