### ISSUE TITLE
[chordpro] Rendre correctement les accords et tablatures

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#74]
La branche chordpro a été intégrée, mais il reste toujours la gestion des accords et des tablatures. Je te (@Luthaf) laisse au moins étudier la syntaxe des deux : je ne sais pas si on peut copier bêtement du chordpro vers LaTeX, ou s'il y a un traitement à faire.

**Comment by paternal** [comment]
Pour l'analyse du format chordpro, je devrais avoir mes réponses par ici : patacrep/patanet#99. Pour le rendu LaTeX, voir la référence de songs : [pour les accords](http://songs.sourceforge.net/songsdoc/songs.html#sec5.3) et [pour les tablatures](http://songs.sourceforge.net/songsdoc/songs.html#sec6) (les *tablatures* correspondent bien aux *chord grids* ?).

- Accords : J'ai l'impression que (``[A-G]{#|b}{m|dim|maj|sus}{digit}{/[A-G]{#|b}}``) : 
  - `A-G` sont recopiés tels quels ;
  - `#` est copié, tandis que `b` est converti en `&` ;
  - `m`, `maj` et `sus` sont copiés tels quels. Que faire de `dim` ?
  - `digit` est laissé tel quel ;
  - `/[A-G]{#|b}` : Qu'en faire ? Je le converti en remplaçant `/` par une espace ?
- Tablatures (`{define: <chord> base-fret <base> frets <Low-E> <A> <D> <G> <B> <E> fingers <Low-E> <A> <D> <G> <B> <E>} key <KEY>`) :
  - `chord` est converti selon les mêmes règles que plus haut ;
  - `<base>` correspond au `fret` de songs ;
  - `<Low-E> <A> <D> <G> <B> <E>` correspond au `strings` de songs (en remplaçant `x` par `X`) ;
  - le second `<Low-E> <A> <D> <G> <B> <E>` correspond au `fingering` de songs (en remplaçant les `-` par `X`) ;
  - que dois-je faire du `KEY` ?

Merci pour votre aide…

**Comment by Luthaf** [comment]
> (les tablatures correspondent bien aux chord grids ?)

Ce qui est appelé *Guitar tablature diagrams* dans la doc de Song correspond aux diagrammes d'accords, et à ce que la doc de `Songsheet Generator` appelle *chord grid*.

>  m, maj et sus sont copiés tels quels. Que faire de dim ?

Gardé tel quel aussi.

>  /[A-G]{#|b} : Qu'en faire ? Je le converti en remplaçant / par une espace ?

Je garderai tel quel aussi, en remplaçant simplement `b` par `&`. Le `/` doit être gardé aussi.

De manière plus général, cette regex n'est pas complète. Le [dernier exemple](http://songs.sourceforge.net/songsdoc/songs.html#sec5.3) ici par exemple n'est pas géré. Je conseillerai de garder les noms d'accords tel quel au complet, en substituant simplement les `b` par des `&`.

**Comment by Luthaf** [comment]
> que dois-je faire du KEY ?

Le KEY est spécifique à `Songsheet Generator` et peut donc être soit ignoré, soit produire une erreur. Je suis pour produire une erreur, c'est une extension non standard que l'on a pas besoin de supporter.
