### ISSUE TITLE
Format Songbook

### ISSUE THREAD

**Issue by LaTruelle** [patacrep/patacrep#78]
Est-ce que le format d'un songbook est du json valide ? Dans ce cas, cela me permettrait de passer des fonctions de patagui de QtScript vers QJson (qui est supporté depuis Qt5)

cf. https://github.com/patacrep/patagui/issues/147 

Est-ce que le format des fichiers songbook ont changé entre la version 3.7.2 et la v4 ou pas ? Si oui, je réécrirai le module qui lit/écrit les fichiers dans patagui.

**Comment by Luthaf** [comment]
Yep, c'est du Json valide ! On utilise d'ailleurs l'implémentation Python pour [les lire](https://github.com/patacrep/patacrep/blob/621facd21dacfebabbc1f5080b234a6de1f326c0/patacrep/songbook.py#L109). 

Normalement le format n'a pas changé entre la 3.7.2 et la 4.0, i.e. les anciens fichiers .sg sont en théorie toujours compatibles avec la 4.0.

**Comment by paternal** [comment]
> les anciens fichiers .sg sont en théorie toujours compatibles avec la 4.0.

Le fichier json de patacrep 3.7 peut toujours être lu avec patacrep 4.0, mais pas sûr qu'il soit interprété correctement. Par exemple, on a changé la manière d'inclure les chansons.

> Est-ce que le format des fichiers songbook ont changé entre la version 3.7.2 et la v4 ou pas ? Si oui, je réécrirai le module qui lit/écrit les fichiers dans patagui.

Une chose qui a changé, par contre, c'est les templates (nous utilisons maintenant jinja2), et la manière dont sont stockées les informations de templates dans les templates, qui est interprété par patagui pour créer la gui (voir [un exemple](https://github.com/patacrep/patacrep/blob/621facd21dacfebabbc1f5080b234a6de1f326c0/patacrep/data/templates/patacrep.tex#L22-64)).

**Comment by paternal** [comment]
J'ai l'impression que l'on peut fermer ce ticket. Ré-ouvrez si je me trompe.
