### ISSUE TITLE
Suppression de vcover

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#81]
Pour rappel, on jongle avec des `cover` et `vcover` pour les couvertures d'album : l'une va chercher dans le répertoire du fichier courant, l'autre dans le chemin normal de latex (éventuellement modifié avec `\graphicspath`). C'est trop compliqué. Je pense que l'on peut s'en débarasser, grâce à [ce bout de code](http://www.grappa.univ-lille3.fr/FAQ-LaTeX/9.5.html). Avec ça, la compilation du `main.tex` suivant fonctionne, avec : 

~~~
\documentclass{article}

\usepackage{graphicx}
\graphicspath{{images/}}

\makeatletter
\def\import{\begingroup
  \protected@edef\@tempa{\endgroup
    \noexpand\@import{\@ifundefined{input@path}{}{\input@path}}%
    {\@ifundefined{Ginput@path}{}{\Ginput@path}}}%
  \@tempa}
\def\@import#1#2#3#4{%
  \def\input@path{{#3}#1}\def\Ginput@path{{#3}#2}%
  \input{#4}%
  \def\input@path{#1}\ifx\input@path\@empty \let\input@path\@undefined \fi
  \def\Ginput@path{#2}\ifx\Ginput@path\@empty \let\Ginput@path\@undefined \fi
}
\makeatother

\begin{document}


\includegraphics{root}
\includegraphics{images}

\import{folder/}{song}

\end{document}
~~~
le fichier `folder/song` suivant : 

~~~
\includegraphics{folder}
\includegraphics{images}
\includegraphics{root}
~~~

et le répertoire suivant :

~~~
$ tree
.
├── folder
│   ├── folder.jpg
│   └── song.tex
├── images
│   └── images.jpg
├── main.tex
└── root.jpg
~~~

Ce qu'il faut remarquer :

* le fichier `song.tex` n'est pas inclus avec `\input`, mais `\import` ;
* à l'intérieur, un `\includegraphics` va chercher les images à la fois dans le répertoire du fichier importé, dans le répertoire du fichier principal, et dans les répertoires désignés par `\graphicspath`.

Du coup, on doit pouvoir :

* supprimer `vcover` ;
* simplifier le code derrière `\lilypond` et `\image`.

**Comment by Luthaf** [comment]
Ça me semble bien !

**Comment by oliverpool** [comment]
:+1:

**Comment by paternal** [comment]
C'était bien plus simple que je ne le pensais. :)
