### ISSUE TITLE
Permettre de définir la taille des images

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#83]
Voir https://github.com/patacrep/patadata/pull/21#issuecomment-137925840

Réfléchir aux unités autorisées ; permettre aussi `%`, qui serait traduit correctement selon le format de sortie ?

**Comment by paternal** [comment]
Un jour, j'implémenterai cela. Quelle syntaxe choisir ? Pour la taille des images, je vois plusieurs « unités » qui peuvent être utiles :
- absolu : centimètres ;
- relatif à la police : [em](https://fr.wikipedia.org/wiki/Cadratin) ;
- relatif à la taille initiale de l'image : « Rendre l'image deux fois plus petite » ;
- relatif à l'espace disponible : « Prendre la moitié de l'espace horizontal/vertical disponible » (je ne sais pas comment implémenté « ... vertical ... » en LaTeX).
Nous ne sommes pas obligé de permettre tout cela, mais il faut trancher.

Ensuite, quelle syntaxe pour les tailles qui ne respectent pas les proportions de départ ? @Oliverpool proposait (https://github.com/patacrep/patadata/pull/21#issuecomment-137925840) :

~~~chordpro
{image: fichier.png 5cm 3cm}
{image: fichier.png 3cm} # (hauteur)
{image: fichier.png auto 3cm} # (largeur)
{image: fichier.png}
~~~

On peut aussi imaginer (par analogie avec ce qui se fait en LaTeX et CSS) :

~~~chordpro
{image: fichier.png width=5cm height=3cm}
{image: fichier.png height=3cm width=5cm} # Identique au précédent
{image: fichier.png height=3cm fichier.png} # Largeur proportionnelle
{image: fichier.png} # Taille par défaut
{image: "fichier avec espaces.png"} # Espaces dans le nom de fichier.
~~~

J'ai une préférence pour le deuxième cas (plus proche de ce qui se fait en LaTeX et HTML).


Pour les unités, je propose :

- `3cm` : Absolu, en centimètres (quelle est la liste des unités que l'on autorise ?)
- `3em` : Relatif à la taille de la police (se traduit facilement en LaTeX et HTML)
- `50%` ou `x0.5` : Réduire de moitié la taille de l'image.
- `???` : Prendre la moitié de l'espace horizontal.
- impossible : Prendre la moitié de l'espace vertical.

Je ne sais pas quelle syntaxe utiliser pour les derniers cas.

À vos commentaires !

**Comment by paternal** [comment]
Autre idée de syntaxe :

~~~chordpro
{image: foo.png scale=1x2} # Doubler la taille en hauteur, mais conserver la même en largeur
{image: foo.png scale=x2} # Doubler la taille en hauteur, et en largeur de manière proportionnelle
{image: foo.png scale=3x} # Tripler la taille en largeur, et en hauter de manière proportionnelle
{image: foo.png scale=3} # Identique au précédent

{image: foo.png size=2cmx3cm} # Afficher l'image au format 2cm par 3cm. Les unités acceptées sont un sous-ensemble de celles acceptées à la fois en LaTeX et en html, à savoir : cm, em et ex devraient suffire.
{image: foo.png size=x3cm} # Fixer la hauteur, et la largeur de manière proportionnelle
{image: foo.png size=2cmx} # Fixer la largeur, et la hauteur de manière proportionnelle
{image: foo.png size=2cm} # Identique au précédent

{image: foo.png fill=50%} # L'image prend 50% de la largeur disponible, et la hauteur de manière proportionnelle.
{image: foo.png fill=50%x} # Identique au précédent
{image: foo.png fill=x50%} # Non supporté en LaTeX. En html : remplit 50% de la hauteur disponible ?
{image: foo.png fill=50%x25%} # Mélange des deux précédents.
~~~

Cette syntaxe me convient davantage.

**Comment by oliverpool** [comment]
Pour le `scale`, les 3 premier cas sont redondants : "doubler la hauteur, et en largeur proportionnellement" revient simplement à doubler la hauteur et la largeur. Seul le dernier cas est particulier, mais je pense qu'il n'est pas très pertinent (il déforme l'image).

Pour les `size`, est-ce qu'on pourrait pas utiliser des variables équivalentes à `\textwidth` : `width=0.5\textwidth` ? (du coup, je serait plutôt favorable à des arguments `width` et `height` : si un seul des deux est spécifié, l'autre est proportionnel).

Ou alors les pourcentages sont par rapport à `\textwidth` : `width=50%`.

---

Autre proposition: on utilise exclusivement `width` et `height` avec les unités suivantes:
- pas d'unité => mise à l'échelle `width=2` double la largeur de l'image
- cm, em, ex = > largeur spécifiée par l'unité
- % => par rapport à la largeur/hauteur de la page

Si un seul est spécifié, l'autre est proportionnel.

**Comment by paternal** [comment]
> Seul le dernier cas est particulier, mais je pense qu'il n'est pas très pertinent (il déforme l'image).

LaTeX le permet, HTML le permet, je me dis qu'on pouvait le permettre aussi. En plus, tu sembles dire qu'on pourrait aussi le permettre dans ta dernière phrase : « Si un seul est spécifié, l'autre est proportionnel. » J'en déduis que si les deux sont spécifiés, ça n'est pas proportionnel ?


Mon problème si l'unité définit la méthode de calcul (ce qui était [ma proposition précédente](https://github.com/patacrep/patacrep/issues/83#issuecomment-170255037) et la fin de ton message), c'est que l'unité `%` me parait ambigüe : ça ne me parait pas évident de savoir s'il s'agit d'un pourcentage de l'image (`50%` veut dire : on diminue l'image de moitié) ou de l'espace disponible (`50%` veut dire : l'image remplit la moitié de l'espace disponible). J'ai peur que ça soit le genre de convention dont il est très difficile de se rappeler, et qui force à se référer à la doc à chaque usage.

Mais ma (dernière) proposition ne me satisfait pas complètement non plus…

**Comment by paternal** [comment]
On peut aussi se dire que l'option `fill` est inutile, et non supportée. Comme ça, 50% veut forcément dire « Réduire de moitié la taille de l'image ».

**Comment by oliverpool** [comment]
Du coup je pensais à `.5` pour 50% de la taille de l'image et `50%` pour 50% de la taille de la page (mais tu as tout à fait raison que c'est pas forcément très intuitif)

**Comment by paternal** [comment]
*Note à moi même* : Liste des unités communes à LaTeX et HTML : cm em ex in mm pc pt (ceci ne veut pas dire qu'on les supporte toutes).
