### ISSUE TITLE
Permettre la définition d'accords « spéciaux »

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#84]
Voir https://github.com/patacrep/patacrep/pull/79#issuecomment-139654926

**Comment by oliverpool** [comment]
Je pense que ChordPro suit en théorie la démarche inverse: la plupart des accords sont déjà connus, et `{define}` ne sert **qu'a** définir des accords spéciaux.

Au niveau de la transition, ça devient assez violent du coup, puisqu'il faut supprimer tous les accords 'non-spéciaux'.
Au niveau de l'implémentation, c'est aussi pas forcément facile puisqu'il faut alors lister les accords utilisés dans un chant et les inclure au début de celui-ci...

**Comment by oliverpool** [comment]
Par exemple:
http://ukegeeks.com/show-all-chords.htm
http://blog.ukegeeks.com/users-guide/how-do-i-define-my-own-chords/

**Comment by paternal** [comment]
Je me sens incompétent là-dessus (je ne sais pas jouer de la guitare et lire des accords), donc je vous (@oliverpool, @Luthaf) laisse discuter de ça.

**Comment by Luthaf** [comment]
> Je pense que ChordPro suit en théorie la démarche inverse: la plupart des accords sont déjà connus, et {define} ne sert qu'a définir des accords spéciaux.

Je ne suis pas fan de cette manière de faire, elle est contraire au fonctionnement actuel des chansons. Mais c'est vrai qu'une fonction `show_all_chords` à placer au début des carnet (comme dans les diap') serait cool !

**Comment by oliverpool** [comment]
> elle est contraire au fonctionnement actuel des chansons

Certes, mais le fonctionnement actuel est un peu contraire à la façon de faire de ChrodPro ^^.

Je vois deux possibilités :
- on convertit tout en accords "normaux" et plus tard (lorsqu'on aura du temps) on se débrouille pour reconnaître les accords non-spéciaux (via une BDD des accords "standards") et les retirer de la compilation (selon les options de la compilation)
- on rajoute un mot-clé (optionnel) `special` à la fin des `define` (ce qui dévie un peu du standard ChordPro), et plus tard on peut faire un traitement similaire

**Comment by paternal** [comment]
> on rajoute un mot-clé (optionnel) special à la fin des define (ce qui dévie un peu du standard ChordPro), et plus tard on peut faire un traitement similaire

Cette solution me chiffonne toujours, car elle brise l'interopérabilité avec les autres logiciel pour une fonctionnalité qui me parait importante. Que penses-tu (si c'est cette alternative qui est choisie), de [ma proposition](https://github.com/patacrep/patacrep/pull/79#issuecomment-139654926) de ne pas toucher aux `define`, mais d'ajouter une nouvelle directive `define-special`?

**Comment by oliverpool** [comment]
Cette troisième solution me convient tout à fait !
