### ISSUE TITLE
Comment faire la différence entre les accords pour guitare et ukulélé ?

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#85]
… qui correspondent aux `\gtab` et `\utab` en $LaTeX$ ? Sans pour autant casser l'interopérabilité des `{define: FOO}`.

**Comment by oliverpool** [comment]
Le site suivant http://blog.ukegeeks.com/users-guide/chordpro-markup-reference/ utilise simplement des `define` avec 4 cordes.
