### ISSUE TITLE
Implémenter `{newline}`

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#86]
… pour permettre des sauts de lignes dans les couplets.

**Comment by oliverpool** [comment]
Comment est-ce que c'est censé se traduire au niveau de LaTeX ?

**Comment by Luthaf** [comment]
Par un `\newline` je pense.

**Comment by paternal** [comment]
Il faut voir si `\newline` est disponible dans l'environnement `verse`. Sinon, c'est `verse` puis `verse*`.

**Comment by oliverpool** [comment]
> Sinon, c'est verse puis verse*.

Sauf si on était dans un bridge ou un chorus
Et il faudra penser à ferme le `verse*`

Bref, rendre `\newline` disponible (ou équivalent) me parait plus facile

**Comment by paternal** [comment]
On n'a peut-être même pas besoin de s'embêter avec des `verse*` : les deux syntaxes suivantes fonctionnent.

~~~latex
\begin{verse}
    tagada\newline

    tsoin tsoin
\end{verse}

\begin{verse}
    tagada
    ~\\
    tsoin tsoin
\end{verse}
~~~

La seconde sera peut-être plus simple à mettre en œuvre.

**Comment by paternal** [comment]
Pour info : Travail en cours sur la [branche newline](https://github.com/patacrep/patacrep/tree/newline).
