### ISSUE TITLE
Permettre l'analyse des accords dans les commentaires

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#87]
Utiliser des blocs `{start_of_comment}` / `{start_of_guitar_comment}`, et ne pas analyser les directives `{comment: FOO}` ?

Voir à partir de https://github.com/patacrep/patadata/pull/18#issuecomment-137137365.

**Comment by oliverpool** [comment]
Je pense qu'on devrait pouvoir se passer de `{start_of_comment}` / `{start_of_guitar_comment}` en reformulant:
- il y a peu de `{comment}` avec des accords (voire aucun ? - à vérifier)
- les `{guitar_comment}` avec des accords, sont la plupart du temps, juste des accords (répétés parfois) qui ne doivent seulement pas apparaître sur la version sans accords du carnet de chant (donc qu'on pourrait simplement afficher tel-quel? Comment gère le paquet `songs` dans ce cas?).

En résumé je pense qu'il faudrait s'en occuper pendant la transition LaTeX -> ChordPro.

**Comment by paternal** [comment]
Du coup on peut fermer sans rien changer au code ? Ça me convient tout à fait (je freine des quatre fers depuis le début pour ne pas avoir à implémenter cela :stuck_out_tongue: ).

**Comment by oliverpool** [comment]
Le problème, c'est que le paquet `song` à besoin d'une indiquation pour dire qu'il y a une ligne (ou un couplet) sans paroles: https://github.com/patacrep/patadata/blob/master/songs/adele/lovesong.sg#L46

Si c'est possible de reconnaître ces "couplets" automatiquement, ça serait génial ! (quitte à utiliser un `verse*` pour éviter la numérotation et les caractères latéraux associés au `bridge`)

**Comment by paternal** [comment]
Et ceci ne fonctionne pas ?

~~~chordpro
Un [A]vers
[Bb]avec des paroles

[Cm A# G# G]

Un [B]troisième vers
avec [C]aussi des paroles
~~~

**Comment by oliverpool** [comment]
De mémoire le rendu pdf n'est pas top: le paquet song affiche les accords comme si il y avait du texte ("au dessus" d'une ligne de texte invisible).

Avec `\musicnote {\nolyrics`, il affiche les accords sur la ligne, avec un fond particulier.

Si le parseur est capable de reconnaitre une ligne avec seulement une liste d'accords (comme ton exemple), alors il pourrait ajouter le bon environnement LaTeX (et ça serait top!)

**Comment by paternal** [comment]
> Si le parseur est capable de reconnaitre une ligne avec seulement une liste d'accords (comme ton exemple), alors il pourrait ajouter le bon environnement LaTeX (et ça serait top!)

Ça doit être possible… Dans ma todo liste…

**Comment by oliverpool** [comment]
Je ne suis pas sûr des commandes optimales/minimales à fournir à LaTeX pour que ça marche (mais c'est pas trop difficile à changer).

Je pense que l'on peut restreindre cela à:
un couplet, dont chacune des lignes et un accord (ou une liste d'accords).

Ok:
~~~chordpro
Un [A]vers
[Bb]avec des paroles

[Cm A# G# G]

Un [B]troisième vers
avec [C]aussi des paroles
~~~
~~~chordpro
Un [A]vers
[Bb]avec des paroles

[Cm A# G# G]
[Cm A# G# F]

Un [B]troisième vers
avec [C]aussi des paroles
~~~

---

Pas ok:
~~~chordpro
Un [A]vers
[Bb]avec des paroles
[Cm A# G# G]

Un [B]troisième vers
avec [C]aussi des paroles
~~~
~~~chordpro
Un [A]vers
[Bb]avec des paroles

[Cm A#] [G# G]

Un [B]troisième vers
avec [C]aussi des paroles
~~~

**Comment by paternal** [comment]
Voir #105
