### ISSUE TITLE
Remove {start_of_verse}

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#91]
[Actuellement](https://github.com/patacrep/patacrep/blob/master/patacrep/songs/chordpro/test/greensleeves.sgc#L15) le rendu en ChordPro ajoute des `{start/end_of_verse}` qui n'ont (je pense) pas lieu d'être.

Est-ce que je peux les supprimer ou est-ce que c'est voulu ?

**Comment by paternal** [comment]
Non, on peut les supprimer.

**Comment by oliverpool** [comment]
Ok, je m'en occupe

**Comment by oliverpool** [comment]
Le premier commit n'est pas à jour avec master... il faut seulement considérer https://github.com/patacrep/patacrep/compare/fix_verse que je te laisse merger si cela te convient

**Comment by oliverpool** [comment]
Les premiers commits ne sont pas à jour avec master... il faut seulement considérer https://github.com/patacrep/patacrep/compare/fix_verse que je te laisse merger si cela te convient
