### ISSUE TITLE
API d'accès à la classe Song

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#93]
Patanet et patagui ont pour objectif d'afficher et de modifier les information des chants à l'aide d'une interface.

Je suppose que le mieux est d'utiliser la classe Song de patacrep (`ChordproSong` par exemple).

Dans patanet, j'aurai besoin de quelques méthodes supplémentaires:
* rajouter une méthode `get` à `OrderedLifoDict` (avec [possibilité d'un résultat par défaut](https://github.com/patacrep/patanet/pull/137/files#diff-5fa0f5b419c06a5a166e740c049e14e5R74))
* ajouter deux méthodes pour avoir le contenu "brut" (au format ChordPro) de l'entête et du corps du chant (ainsi qu'une méthode qui concatène les deux)
* `get_cover_path` pour récupérer le chemin complet (avec extension) de la jaquette

Est-ce qu'e j'en ai oublié ? Est-ce que vous avez d'autres idées concernant cette "API" ?
@LaTruelle tu as peut-être aussi des suggestions ?

**Comment by paternal** [comment]
> Dans patanet, j'aurai besoin de quelques méthodes supplémentaires:
> * rajouter une méthode `get` à `OrderedLifoDict` (avec [possibilité d'un résultat par défaut](https://github.com/patacrep/patanet/pull/137/files#diff-5fa0f5b419c06a5a166e740c049e14e5R74))

C'est possible…

> * ajouter deux méthodes pour avoir le contenu "brut" (au format ChordPro) de l'entête et du corps du chant (ainsi qu'une méthode qui concatène les deux)

Je ne comprends pas ce que tu veux. Qu'est-ce que tu appelles le contenu "brut" ? Une chaîne de caractères correspondant au code chordpro ? Autre chose ?

> * `get_cover_path` pour récupérer le chemin complet (avec extension) de la jaquette

C'est possible…

**Comment by oliverpool** [comment]
> Qu'est-ce que tu appelles le contenu "brut" ?

Je veux parler du "texte brut" (le code chordpro). Notamment à des fins d'éditions (et de sauvegarde de ces modifications). En effet, l'édition des métadonnées (titre, artiste, accords...) et du corps du chant seront séparées.
Mon idée actuelle: quand l'utilisateur modifie le corps du chant, on concatène les métadonnées (texte brut) avec le nouveau corps du chant et on sauvegarde le tout (d'où mon besoin d'accès au métadonnées et au corps du chant de manière distincte)

Concernant les templates, comment est-ce qu'il est possible d'en créer une qui soit embarquée dans patanet (voire patadata) ?

**Comment by paternal** [comment]
TODO pour moi-même (sauf si une bonne âme me prend de vitesse) : 

- [ ] Ajouter une méthode `get` à `OrderedLifoDict`.
- [ ] Créer une méthode `get_cover_path`.

Pour le reste, quand j'ai écrit le code permettant de produire une chanson en Chordpro ou Latex (qui est utilisé dans les tests), j'ai fait ça avec en tête de pouvoir le faire dans patanet. Ça ne veut pas dire que ça fonctionne déjà, mais que ça fonctionnera à peu de frais.

Pour rendre du HTML, ce que j'imagine, c'est de pouvoir ajouter à je-ne-sais-quelle fonction un argument `template_dir`. Comme ça, quand vous rendez la chanson en HTML dans patanet, vous n'avez qu'à préciser à cet endroit où aller chercher les templates pour faire du HTML.

De même, pour obtenir le code chordrpo du corps de la chanson, vous pouvez écrire un nouveau template à partir des trois dernières lignes de [celui-là](https://github.com/patacrep/patacrep/blob/24d49cb29ef17b18fcc430ac9a8fd7bfcf4eb8a4/patacrep/songs/chordpro/data/chordpro/song), et dire au moment opportun où aller chercher ce template. Idem pour les métadonnées.

**Comment by oliverpool** [comment]
> Pour rendre du HTML, ce que j'imagine, c'est de pouvoir ajouter à je-ne-sais-quelle fonction un argument template_dir. Comme ça, quand vous rendez la chanson en HTML dans patanet, vous n'avez qu'à préciser à cet endroit où aller chercher les templates pour faire du HTML.

En vrai je ne suis pas sûr que cela soit nécessaire : django a déjà sont propre système de templates, et on peut l'utiliser directement (à partir de l'objet `song`). Cela évite notamment de mélanger deux systèmes de templates un peu différents dans patanet (et si des gens sont intéressés, je suis prêt à écrire un template pour patacrep pour un rendu HTML).

> @oliverpool : Tu peux me montrer où et comment (surtout : en manipulant quel type d'objets) va se faire le rendu HTML, pour que je vois comment intégrer au mieux la possibilité de spécifier de nouveaux répertoires de templates ?

Actuellement je me reconstruit un objet `song`: https://github.com/patacrep/patanet/blob/song_edition/generator/songs.py#L47-L72
(d'ailleurs je n'ai aucune idée de ce que doit contenir `config`...)
Et le rendu se fait dans un template django (`content = song`):
https://github.com/patacrep/patanet/blob/song_edition/generator/templates/generator/show_song.html#L38-L94
(`full_content` est affiché à la fin au lieu de seulement le corps du chant)

Rendu actuel:
![2015-09-17-090115_1366x768_scrot](https://cloud.githubusercontent.com/assets/3864879/9927026/fde49b96-5d1a-11e5-89d3-9cf4359cf0f3.png)

-----
L'idéal serait de réduire la fonction de récupération à deux lignes:
```
    song_model = ChordproSong(datadir, relpath)
    return song_model.parse()
```
Ce qui est un peu utopiste car on a traitement spécial pour `cover_url` (url de l'image d'album) et pour les `chords` (quoique ça doit être faisable en rajoutant un attribut `pretty_key` qui remplace les # et les &).

**Comment by oliverpool** [comment]
@paternal je vais implémenter les *getters* (et mettre à jour ta TODO list en conséquence)

**Comment by paternal** [comment]
@oliverpool Si tu veux te mettre à `get_cover_path` avant moi, il faut regarder du côté de [`search_image()`](https://github.com/patacrep/patacrep/blob/7d7bdd0417a27e30f2aca7a71202ac47547358d8/patacrep/songs/__init__.py#L206-L240) (en voyant quelle partie du code est factorisable). Pour info, j'ai pris le parti de dire que les images en chordpro doivent être définies avec leur extension (donc `tagada.png` et non pas `tagada` comme en LaTeX).

**Comment by oliverpool** [comment]
oups...
Je viens de copier/coller ma méthode qui cherche l'extension (soit jpg, soit png)
Et en partant du principe que l'image est dans le même dossier que le fichier <- c'est problématique ?

**Comment by oliverpool** [comment]
Et j'ai l'impression que mon implémentation (ou mes noms de variables) pourraient être améliorés...

**Comment by paternal** [comment]
> Je viens de copier/coller ma méthode qui cherche l'extension (soit jpg, soit png)

Il faut s'implement s'accorder, sinon l'image affichée sur le web ne serait pas la même que celle affichée dans le carnet. Il faut simplement décider si on autorise ou non une image sans suffixe.

> Et en partant du principe que l'image est dans le même dossier que le fichier <- c'est problématique ?

Oui. Lors de la compilation, Patacrep et LaTeX vont chercher les images : 

- d'abord dans le même dossier que la chanson ;
- si elle n'est pas trouvée, dans les datadir ;
- enfin, à la racine du projet.

**Comment by oliverpool** [comment]
Merci pour les précisions, effectivement il vaut mieux afficher la même image !

Actuellement la plupart des fichiers n'ont pas d'extension (si ce n'est tous ?).
Si on impose l'extension, la conversion devient plus difficile.

Je peux changer ma méthode comme ceci:
```
        extensions = ['', 'jpg', 'png']
        for extension in extensions:
            if search_image(filepath + extension):
                return filepath + extension
```
(à quelques adaptations près, notamment la valeur de retour)

Ça cherche le nom de fichier tel quel (si il a une extension il sera vite trouvé) puis il essaye avec des extensions.

Est-ce que ça conviendrait ?

**Comment by oliverpool** [comment]
Par exemple: https://github.com/patacrep/patacrep/commit/044d9570aea9a8b28e7db8247e5f8b067a88e8a8

Cela casse des test, car `seach_image` retourne `None` si le fichier n'est pas trouvé au lieu du nom original.

**Comment by paternal** [comment]
Je fais une petite pause là-dessus, et je regarderai plus tard (j'ai des cours à préparer et des biberons à donner).

**Comment by oliverpool** [comment]
La nuit portant conseil, voici une implémentation que je trouve plus élégante: https://github.com/patacrep/patacrep/compare/api_getter (et qui passe tous les tests :-)

**Comment by paternal** [comment]
J'ai regardé vite fait, et ça m'a l'air très bien.

**Comment by oliverpool** [comment]
Suite de la discussion dans les issues concernées.
