### ISSUE TITLE
Gestion des articles des noms d'artiste et internationalisation

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#94]
*Évoqué dans #88*
Il y a un certain nombre d'artistes commençant par 'The ', 'Le ', 'Les ', 'La ', est-ce qu'il serait raisonnable d'ajouter une règle automatique pour que le 'The' soit considéré comme le prénom ?

En l'ajoutant dans `authwords` par exemple.

Par ailleurs, cela soulève le problème des articles dans les autres langues.
Est-ce qu'il serait possible d'adapter les [`compile_authwords`](https://github.com/patacrep/patacrep/blob/authors/test/test_authors.py#L44-L46) en fonction de la langue du chant ?

**Comment by paternal** [comment]
> Il y a un certain nombre d'artistes commençant par 'The ', 'Le ', 'Les ', 'La ', est-ce qu'il serait raisonnable d'ajouter une règle automatique pour que le 'The' soit considéré comme le prénom ?

Je ne comprends pas ce que tu veux dire. Pour le moment (et on est en train [de confirmer cela](https://github.com/patacrep/patacrep/blob/authors/test/test_authors.py#L14)), on considère un mot comme prénom en fonction des espaces, et non pas en fonction de sa signification.

Pareil pour les autres langues : puisuqe les prénoms sont tout ce qui précède le dernier espaces, actuellement, `The Doors`, `Les Chaussettes~noires` et `Las Ketchup` sont correctement analysés, sans avoir à s'occuper de leur langue.

**Comment by oliverpool** [comment]
> `The Doors`, `Les Chaussettes~noires` et `Las Ketchup` sont correctement analysés, sans avoir à s'occuper de leur langue

C'est principalement le `~` qui me gêne et que je ne trouve pas très naturel.
Ma proposition le rend facultatif quand il s'agit "d'un cas d'école" (nom d'artiste commençant par un adjectif de la langue de la chanson).
Et en cas d'exception (où le prénom est "The Foo", dans "The Foo Bar"), alors on peut toujours utiliser le `~`: "The~Foo Bar".

En résumé, je souhaiterai que l'utilisation du tilde ne soit pas la règle, mais seulement pour gérer les exceptions.

**Comment by paternal** [comment]
> En résumé, je souhaiterai que l'utilisation du tilde ne soit pas la règle, mais seulement pour gérer les exceptions.

Jusqu'à présent, autant que possible, la gestion de l'index (puisque c'est de cela qu'il s'agit) était compatible avec celle faite par le paquet LaTeX [songs](http://songs.sourceforge.net/). Ajouter cette fonctionnalité briserait cette compatibilité.



> C'est principalement le `~` qui me gêne et que je ne trouve pas très naturel.

Ça ne me choque pas ; mais je suis un geek habitué à échapper des caractères… En solution intermédiaire, est-ce qu'on pourrait imaginer de ne faire cela que pour le format chordpro ?

**Comment by oliverpool** [comment]
Ca peut être une idée: lors du rendu ChordPro -> LaTeX, on rajoute des tildes dans le nom de famille (pour forcer la main au paquet songs)

**Comment by oliverpool** [comment]
On pourrait en profiter pour supporter soit `\ `, soit `~` dans ChordPro (pour éviter le mélange des deux).

Je suis en faveur du `~`.

**Comment by paternal** [comment]
> Ca peut être une idée: lors du rendu ChordPro -> LaTeX, on rajoute des tildes dans le nom de famille (pour forcer la main au paquet songs)

Mais ça ne serait pas au niveau du rendu, mais avant : les auteurs sont analysés (pour l'index) avant. Le moment de l'analyse du fichier me semble être le plus pertinent.

Et après réflexion, je pense qu'on peut faire ça pour le LaTeX aussi : ça me parait bizarre de faire ça avec un des formats de fichiers et pas avec l'autre…

**Comment by paternal** [comment]
> On pourrait en profiter pour supporter soit \, soit ~ dans ChordPro (pour éviter le mélange des deux).
> 
> Je suis en faveur du ~.

Idem. Pas de commentaires pour l'espace insécable ?

**Comment by oliverpool** [comment]
Je ne les manipule pas fréquemment (à part pour des hacks). 
Du coup je préférerai éviter leur utilisation automatique (sans l'interdire pour les aficionados) 
Et dans patanet, utiliser les `~` dans sur le serveur (et voir comment on gère le côté utilisateur)

**Comment by oliverpool** [comment]
> C'est principalement le `~` qui me gêne et que je ne trouve pas très naturel.

Après y avoir réfléchi de nouveau, on peut laisser tel-quel (c'est à dire forcer l'utilisation du `~`).
Sur patanet, il suffit de faire des champs `firstname` et `lastname` et de remplacer les espaces internes par `~`, puis de les concaténer avec ` ` (un espace).
