### ISSUE TITLE
Gestion des langues des chants

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#95]
*Un peu dans la même veine que #94*
Actuellement la balise `{language}` de chordpro accepte `french`, `german`, `english`...

Est-ce qu'il ne serait pas pertinent d'utiliser un [code langue](https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1) avec deux lettres ? (`fr`, `de`, `en`...) *[le code peut aller jusqu'à 7 lettres apparemment]*

Actuellement je n'ai trouvé aucun programme chordpro qui évoque une telle directive (donc on est assez libre sur ce point).

Pour django ça serait [assez pratique](https://github.com/django/django/blob/master/django/conf/global_settings.py#L50).

---
Il me semble qu'on avait déjà convenu qu'il ne devait y avoir qu'une seule langue par chanson (la langue principalement utilisée)

**Comment by Luthaf** [comment]
Pourquoi pas !

**Comment by paternal** [comment]
L'intérêt des noms complets, c'est qu'ils sont passés directement à LaTeX (en argument du paquet Babel) sans traitement. Si on passe à `fr`, `de` etc., il faudra faire un traitement à ce niveau là. Il existe sûrement un outil capable de faire la conversion nom complet ↔ abbréviation, pour ne pas refaire ça nous même (peut-être même [locale](https://docs.python.org/3.4/library/locale.html)) ?

**Comment by oliverpool** [comment]
Lors de l'écriture du template LaTeX, on peut avoir un mappage entre le code langue et le nom babel (dont une liste apparemment exhaustive est disponible : [en page 2](https://tug.org/pracjourn/2007-1/gregorio/gregorio.pdf) - certains sont des synonymes)

**Comment by oliverpool** [comment]
Dans un premier temps, on peut faire le mappage pour les seules langues utilisées (`fr, de, en` ?)

**Comment by paternal** [comment]
Le paquet Python [babel](http://babel.pocoo.org/) permet d'obtenir un nom de langage à partir de la locale : 

~~~python
>>> import babel
>>> babel.Locale("fr").get_language_name("en").lower()
'french'
>>> babel.Locale("en").get_language_name("en").lower()
'english'
>>> babel.Locale("el").get_language_name("en").lower()
'greek'
>>> babel.Locale("es").get_language_name("en").lower()
'spanish'
~~~

Par contre, le nom du langage ne correspond pas forcément exactement à ce qui est attendu par le paquet LaTeX babel (par exemple, `babel.Locale("en_US").get_language_name("en").lower()` donne `u.s. english` alors que LaTeX attend plutôt `USenglish`. Du coup, j'ai l'impression que cette idée est mauvaise : corriger les erreurs nous prendrait plus de temps que réaliser le mappage nous-même.

Finalement, puisque la liste des langages supportés par Babel n'est pas si longue (voir [pages 18 et 19](http://ctan.mines-albi.fr/macros/latex/required/babel/base/babel.pdf) pour une autre source), réaliser la correspondance nous-même ne serait peut-être pas si compliqué.

Je pense que le mieux est de prendre comme entrée les locales (`en`, `fr`, `en_UK`, `el`, etc.) et de convertir pour LaTeX. On interdit les langages inconnus (par notre système), ou on les remplace par un langage par défaut ?

**Comment by Luthaf** [comment]
> Je pense que le mieux est de prendre comme entrée les locales (en, fr, en_UK, el, etc.) et de convertir pour LaTeX. On interdit les langages inconnus (par notre système), ou on les remplace par un langage par défaut ?

Ça me parait bien aussi. Je pense que le mieux pour les langues inconnues est d'envoyer un warning, et d'utiliser un langage par défaut. On n'a pas non plus de millions de langues à gérer =)

**Comment by oliverpool** [comment]
> On n'a pas non plus de millions de langues à gérer =)

Et d'après ce que j'ai compris, c'est principalement pour l'hyphenation dans les chants.

Pour le reste, ça me va !

**Comment by oliverpool** [comment]
Quitte à être incompatible, je propose aussi de changer le nom de la directive en `lang` (à la place de language):

```
{lang: en}
```

En effet je trouve `language` assez "littéraire" et donc un peu incohérent avec le "code langue". De plus l'usage de `lang` me parait assez répandu ([notamment pour le html](http://www.w3.org/International/questions/qa-lang-why.en.php)).

Cela permettra aussi au niveau du nom des variables, de savoir si l'on parle du code langue ou du nom pour babel.

**Comment by paternal** [comment]
> Quitte à être incompatible, je propose aussi de changer le nom de la directive en lang (à la place de language):

Les autres balises sont toutes écrites sans abréviation (`start_of_chorus`, etc.), du coup, je trouve ça bien qu'on garde `language` en entier. On peut aussi (comme c'est le cas pour `start_of_chorus` et `soc`) définir un « alias », et avoir `{lang: FOO}` et `{language: FOO}` qui signifient la même chose.

**Comment by oliverpool** [comment]
> définir un « alias », et avoir {lang: FOO} et {language: FOO} qui signifient la même chose

Ca me conviendrait

**Comment by oliverpool** [comment]
(suite de la discussion dans #124)
